Repository musescore/MuseScore, pull requests merged in 2018-09, with the labels that each got.

#3914 fix #274902 #274925: Incorrect chord symbol position
  libmscore/harmony.cpp
  libmscore/textbase.h
Labels: review

#3892 Fix #275386: anchor points not rebuilt after setting autoplacement
  mscore/inspector/inspectorBase.cpp
  mscore/scoreview.h
Labels: review

#3913 Fix #275218: MSVC warnings
  fluid/sfont.cpp
  libmscore/beam.cpp
  libmscore/chord.cpp
  libmscore/cmd.cpp
  libmscore/edit.cpp
  libmscore/excerpt.cpp
  libmscore/figuredbass.h
  libmscore/hairpin.cpp
  libmscore/layout.cpp
  libmscore/layoutlinear.cpp
  libmscore/measure.cpp
  libmscore/part.cpp
  libmscore/pitchspelling.cpp
  libmscore/read300.cpp
  libmscore/rendermidi.cpp
  libmscore/rest.cpp
  libmscore/score.cpp
  libmscore/scoreElement.cpp
  libmscore/shape.cpp
  libmscore/shape.h
  libmscore/skyline.cpp
  libmscore/slur.cpp
  libmscore/textbase.cpp
  libmscore/tie.cpp
  libmscore/tuplet.cpp
  libmscore/undo.cpp
  mscore/exportaudio.cpp
  mscore/importgtp-gp5.cpp
  mscore/importmidi/importmidi.cpp
  mscore/importmidi/importmidi_inner.cpp
  mscore/importmidi/importmidi_lrhand.cpp
  mscore/importmidi/importmidi_lyrics.cpp
  mscore/importmidi/importmidi_meter.cpp
  mscore/importmidi/importmidi_model.cpp
  mscore/importmidi/importmidi_quant.cpp
  mscore/importmidi/importmidi_tuplet_filter.cpp
  mscore/importptb.cpp
  mscore/jackaudio.cpp
  mscore/scoreview.cpp
  mscore/seq.cpp
  mscore/waveview.cpp
  thirdparty/beatroot/CMakeLists.txt
  thirdparty/freetype/CMakeLists.txt
  thirdparty/poppler/CMakeLists.txt
  thirdparty/portmidi/CMakeLists.txt
  thirdparty/rtf2html/CMakeLists.txt
Labels: Priority

#3939 Fix #272241: allow tab to go beyond 24 frets
  fonts/fonts_tablature.xml
  libmscore/stafftype.h
Labels: review

#3937 fix #271616: Fermata tempo is not applied when importing 2.X->3.0 score
  libmscore/layout.cpp
  libmscore/layoutlinear.cpp
  libmscore/measure.cpp
  libmscore/measure.h
  libmscore/read206.cpp
  libmscore/score.cpp
  libmscore/score.h
  mtest/libmscore/compat206/fermata-ref.mscx
  mtest/libmscore/compat206/fermata.mscx
  mtest/libmscore/compat206/tst_compat206.cpp
Labels: review

#3899 Fix #275574: crash when dragging element onto score in (text) edit mode
  mscore/palette.cpp
Labels: Priority, review

#3959 fix #276105: repitch input changes rhythm in drums/percussion instruments
  mscore/musescore.cpp
Labels: review
