Repository musescore/MuseScore, pull requests merged in 2018-10, with the labels that each got.

#3994 fix #268966: Insert measures dialog goes behind main window
  mscore/musescore.cpp
Labels: review

#3991 fix #276076, fix #275808: fix issues related to active tab tracking that led to crashes
  mscore/scoretab.cpp
  mscore/scoretab.h
  mscore/scoreview.cpp
Labels: review

#3979 fix #276392: shift+click to select in foto mode doesn't work
  mscore/events.cpp
  mscore/fotomode.cpp
Labels: review

#4005 fix #276668: missing swing in text palette
  mscore/menus.cpp
Labels: review

#4023 fix #277029 - [MusicXML import] Crash caused by unsupported QVariant
  mscore/importmxmlpass1.cpp
Labels: review

#4024 fix #276441: Multiple articulations on a single note possible
  libmscore/chord.cpp
  libmscore/chord.h
Labels: review

#4009 fix #277055: Add StaffText to a Segment instead of Measure when reading Guitar Pro files
  mscore/importgtp-gp4.cpp
  mscore/importgtp-gp5.cpp
  mscore/importgtp.cpp
  mtest/guitarpro/capo-fret.gp3
  mtest/guitarpro/capo-fret.gp3-ref.mscx
  mtest/guitarpro/capo-fret.gp4
  mtest/guitarpro/capo-fret.gp4-ref.mscx
  mtest/guitarpro/capo-fret.gp5
  mtest/guitarpro/capo-fret.gp5-ref.mscx
  mtest/guitarpro/tst_guitarpro.cpp
  mtest/guitarpro/updateReference
Labels: review

#4012 fix #276670: Crash on mouse press on tablature in Re-Pitch input mode
  libmscore/noteentry.cpp
Labels: Priority

#3978 fix #276363: Corruption on duration change of note in measure with local time signature
  libmscore/cmd.cpp
Labels: review

#4021 fix #233436: Do not search grace notes in different staves when making a tie
  libmscore/utils.cpp
Labels: Priority

#4016 fix #276869: Adding barline with ctrl+doubleclick does not create a split.
  libmscore/element.cpp
  libmscore/element.h
  mscore/editlyrics.cpp
  mscore/palette.cpp
  mscore/palette.h
Labels: review

#4039 fix #276668, fix #277219: "Swing" in Text Palette should be system text
  mscore/menus.cpp
Labels: review

#4049 Convert vtest from old 3.00 format
  vtest/accidental-mirror.mscx
  vtest/articulation-1.mscx
  vtest/bravura-10.mscx
  vtest/bravura-text-1.mscx
  vtest/bravura-text-2.mscx
  vtest/chord-layout-17.mscx
  vtest/drumset-custom-1.mscx
  vtest/emmentaler-10.mscx
  vtest/emmentaler-text-1.mscx
  vtest/emmentaler-text-2.mscx
  vtest/gonville-10.mscx
  vtest/gonville-text-1.mscx
  vtest/gonville-text-2.mscx
  vtest/grace-5.mscx
  vtest/harmony-3.mscx
  vtest/mmrest-10.mscx
  vtest/musejazz-1.mscx
  vtest/musejazz-9.mscx
  vtest/musejazz-text-1.mscx
  vtest/musejazz-text-2.mscx
  vtest/pedal-1.mscx
  vtest/percussion-grace.mscx
  vtest/slashed_chord-layout-12.mscx
  vtest/slashed_chord-layout-7.mscx
  vtest/slashed_grace-3.mscx
  vtest/slashed_noteheadposition-1.mscx
  vtest/slurs-10.mscx
  vtest/slurs-5.mscx
  vtest/slurs-6.mscx
  vtest/slurs-7.mscx
  vtest/slurs-8.mscx
  vtest/slurs-9.mscx
Labels: review

#3984 fix #113051: Arpeggio playback should not depend on tempo
  libmscore/arpeggio.cpp
  libmscore/arpeggio.h
  libmscore/rendermidi.cpp
  libmscore/score.cpp
  libmscore/score.h
  mscore/inspector/inspectorArpeggio.cpp
  mscore/inspector/inspector_arpeggio.ui
  mtest/libmscore/midi/testArpeggio-ref.mid
  mtest/libmscore/midi/testArpeggio.mscx
  mtest/libmscore/midi/tst_midi.cpp
Labels: Priority

#4057 make args to msvc_build.bat being case insensitive
  msvc_build.bat
Labels: review

#3882 Fix #274839: Add capo setting to staff text
  libmscore/note.cpp
  libmscore/rendermidi.cpp
  libmscore/score.h
  libmscore/staff.cpp
  libmscore/staff.h
  libmscore/stafftextbase.cpp
  libmscore/stafftextbase.h
  mscore/events.cpp
  mscore/exportmidi.cpp
  mscore/file.cpp
  mscore/propertymenu.cpp
  mscore/stafftext.ui
  mscore/stafftextproperties.cpp
Labels: under discussion

#3975 fix #276385: hairpin edit mode positioning issue
  libmscore/hairpin.cpp
Labels: review, under discussion

#3811 fix #273601: Updated UI for pianoroll editor.
  libmscore/cmd.cpp
  libmscore/score.h
  mscore/CMakeLists.txt
  mscore/events.cpp
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/pianokeyboard.cpp
  mscore/pianokeyboard.h
  mscore/pianolevels.cpp
  mscore/pianolevels.h
  mscore/pianolevelschooser.cpp
  mscore/pianolevelschooser.h
  mscore/pianolevelsfilter.cpp
  mscore/pianolevelsfilter.h
  mscore/pianoroll.cpp
  mscore/pianoroll.h
  mscore/pianoruler.cpp
  mscore/pianoruler.h
  mscore/pianotools.cpp
  mscore/pianoview.cpp
  mscore/pianoview.h
  mscore/preferences.cpp
  mscore/preferences.h
  mscore/scoreview.cpp
  mscore/scoreview.h
Labels: Priority

#4059 add missing break statement
  libmscore/arpeggio.cpp
Labels: review

#4055 fix #109661: pageSettings are not applied to excerpts
  libmscore/score.cpp
  libmscore/score.h
  mscore/musescore.cpp
  mscore/pagesettings.cpp
  mscore/pagesettings.h
Labels: review

#4052 fix #274247, fix #110181: use effective pitches of notes when calculating playback of trills and ornaments
  libmscore/note.cpp
  libmscore/rendermidi.cpp
  mtest/libmscore/midi/testOrnamentsTrillsOttava-ref.txt
  mtest/libmscore/midi/testOrnamentsTrillsOttava.mscx
  mtest/libmscore/midi/tst_midi.cpp
Labels: review

#4002 fix #276526: play panel position not restored on toggle
  mscore/musescore.cpp
  mscore/playpanel.cpp
Labels: review

#4053 fix #274870: fix resetting shortcuts
  mscore/musescore.cpp
  mscore/prefsdialog.cpp
  mscore/shortcut.cpp
  mscore/shortcut.h
Labels: review

#3545 Fix a crash in ScoreBrowser on systems with single-click items activation turned on
  all.h
  mscore/scoreBrowser.cpp
  mscore/scoreBrowser.h
Labels: Priority

#4006 fix #276689: Add a timewise note input mode to MuseScore UI
  libmscore/cmd.cpp
  libmscore/input.h
  libmscore/noteentry.cpp
  libmscore/score.h
  mscore/data/icons/note_timewise.svg
  mscore/globals.h
  mscore/icons.cpp
  mscore/icons.h
  mscore/musescore.cpp
  mscore/musescore.qrc
  mscore/shortcut.cpp
Labels: review, under discussion

#4033 fix #277030: Crash on changing a property of bracket in a part in Inspector
  libmscore/layout.cpp
Labels: review

#3322 Add AppData file
  CMakeLists.txt
  build/Linux+BSD/mscore.appdata.xml.in
Labels: review

#4040 fix #277159: border radius and other text frame attributes lost from MS2 to 3
  libmscore/read206.cpp
Labels: review

#3997 fix #276587: Style lost for default alignment of text
  libmscore/style.cpp
Labels: Test needed, review

#4015 fix #277016: Changing behavior of reading GTP file with incomplete measure
  mscore/importgtp-gp6.cpp
  mtest/guitarpro/UncompletedMeasure.gpx
  mtest/guitarpro/UncompletedMeasure.gpx-ref.mscx
  mtest/guitarpro/tst_guitarpro.cpp
Labels: Test needed, review
