Repository musescore/MuseScore, pull requests merged in 2018-12, with the labels that each got.

#4246 fix #278943: Can't copy tuplet to last beat of measure
  libmscore/duration.cpp
  libmscore/element.cpp
  libmscore/paste.cpp
  libmscore/tuplet.cpp
  libmscore/tuplet.h
  mscore/importgtp-gp4.cpp
  mscore/importgtp-gp5.cpp
  mscore/importgtp-gp6.cpp
  mscore/importgtp.cpp
  mtest/guitarpro/dotted-tuplets.gp5-ref.mscx
  mtest/guitarpro/testIrrTuplet.gp4-ref.mscx
  mtest/guitarpro/tuplets2.gpx-ref.mscx
  mtest/libmscore/tuplet/split1-ref.mscx
  mtest/libmscore/tuplet/split2-ref.mscx
  mtest/libmscore/tuplet/split3-ref.mscx
  mtest/libmscore/tuplet/split4-ref.mscx
Labels: review

#4273 fixing yet another couple strings...
  libmscore/stafftype.cpp
  libmscore/sym.cpp
  mscore/editstyle.ui
  mscore/importgtp.cpp
  mscore/pianoroll.cpp
Labels: review

#4298 fix #248891: chord symbols transposed incorrectly when score concert, parts not
  libmscore/excerpt.cpp
  libmscore/transpose.cpp
Labels: review

#4312 fix #279386 Crash when pasting measures if number > to last mm rest
  libmscore/paste.cpp
Labels: Test needed, review

#4278 Fix some cases of bad memory access
  libmscore/connector.cpp
  libmscore/connector.h
  libmscore/score.cpp
  libmscore/spanner.cpp
  libmscore/xml.h
  libmscore/xmlreader.cpp
  mscore/workspace.cpp
  mtest/importmidi/tst_importmidi.cpp
Labels: review

#4356 Update readme with new, working link to automated tests in the handbook
  README.md
Labels: review

#4355 fix #279119: frame radius and border width don't scale with spatium
  libmscore/textbase.cpp
Labels: Priority, review

#4364 278068 newline in new text
  libmscore/textedit.cpp
Labels: Priority

#4342 278153 voltas
  libmscore/layout.cpp
  libmscore/layoutlinear.cpp
  mtest/libmscore/midi/testVoltaTemp-ref.mid
Labels: Priority, review

#4346 fix #279172, fix #279448: fix two issues related to beams containing pointer to invalid system
  libmscore/beam.cpp
  libmscore/select.cpp
Labels: Priority, review

#4238 fix #278881 Adding support for muting channels by voice
  mscore/data/icons/mixer-mute-off.svg
  mscore/data/icons/mixer-mute-on.svg
  mscore/mixerdetails.cpp
  mscore/mixerdetails.h
  mscore/mixerdetails.ui
Labels: review, under discussion

#4384 Fix issues with articulation placement
  libmscore/chord.cpp
  mtest/musicxml/io/testNoteAttributes1.xml
Labels: Priority, review

#4386 Complete reordering of the layout sequence
  libmscore/layout.cpp
  libmscore/layoutlinear.cpp
Labels: Priority, review

#4385 Custom chords
  libmscore/chordlist.cpp
  libmscore/undo.cpp
  mscore/editstyle.cpp
  mtest/libmscore/compat114/textstyles-ref.mscx
  share/styles/cchords_muse.xml
  share/styles/cchords_nrb.xml
  share/styles/cchords_rb.xml
  share/styles/cchords_sym.xml
Labels: Priority

#4371 fix#279700 Corruption and bad links using exchange voices on score with parts
  libmscore/edit.cpp
  mscore/excerptsdialog.cpp
  mtest/testscript/scripts/exchange-voice-part.mscx
  mtest/testscript/scripts/exchange-voice-part.script
  mtest/testscript/scripts/exchange-voice-part~undo.mscx
  mtest/testscript/scripts/init/TrebleWithPart.mscx
Labels: Priority, review

#4392 fix #279950, fix #279804, fix #279666: force chord symbol layout
  libmscore/chordrest.cpp
  libmscore/harmony.cpp
  libmscore/harmony.h
  libmscore/layout.cpp
  libmscore/textbase.h
Labels: Priority, review

#4093 fix #276461: Custom text styles in previous versions of MS changed to User-1, User-2 etc.
  libmscore/read206.cpp
  libmscore/score.cpp
  libmscore/score.h
  libmscore/style.cpp
  libmscore/style.h
  libmscore/textbase.cpp
  mscore/editstyle.cpp
  mscore/editstyle.h
  mscore/editstyle.ui
  mscore/inspector/inspector.cpp
  mscore/inspector/inspectorDynamic.cpp
  mscore/inspector/inspectorHarmony.cpp
  mscore/inspector/inspectorText.cpp
  mscore/inspector/inspectorTextBase.cpp
  mscore/inspector/inspectorTextBase.h
Labels: review

#4428 fix #279229 Pianoroll update issues
  mscore/musescore.cpp
  mscore/pianolevels.cpp
  mscore/pianolevels.h
Labels: review

#4438 fix #273302: Fermata loses assignment to voice and direction
  libmscore/chordrest.cpp
  libmscore/fermata.cpp
  libmscore/measure.cpp
  libmscore/paste.cpp
  libmscore/read206.cpp
Labels: review

#4453 fix #280092, fix #279183, fix #279676: clefs-related issues
  libmscore/edit.cpp
  libmscore/layout.cpp
  libmscore/range.cpp
  libmscore/undo.cpp
  libmscore/undo.h
  mtest/libmscore/measure/measure-2-ref.mscx
  mtest/libmscore/measure/measure-5-ref.mscx
Labels: Priority

#4503 fix #280690: Editing slur in a score with parts leads to crash
  libmscore/property.cpp
  libmscore/slur.cpp
  libmscore/slurtie.cpp
Labels: under discussion
