Repository musescore/MuseScore, pull requests merged in 2018-11, with the labels that each got.

#3688 fix #272403: Corruption on pasting a range with a truncated note that requires a tie
  libmscore/paste.cpp
  mtest/libmscore/copypaste/copypaste17-ref.mscx
  mtest/libmscore/copypaste/copypaste20-ref.mscx
Labels: review

#4004 Rework updating excerpts and current view to fix the related issues
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/scoretab.cpp
  mscore/scoretab.h
Labels: review

#4106 Make tab1 active by default
  mscore/musescore.cpp
Labels: review

#4112 Replace diff_match_patch with dtl library for performing text diffs
  CMakeLists.txt
  libmscore/CMakeLists.txt
  libmscore/scorediff.cpp
  mscore/CMakeLists.txt
  mscore/file.cpp
  thirdparty/diff/CMakeLists.txt
  thirdparty/diff/README.txt
  thirdparty/diff/diff_match_patch.cpp
  thirdparty/diff/diff_match_patch.h
  thirdparty/diff/diff_match_patch_test.cpp
  thirdparty/diff/diff_match_patch_test.h
  thirdparty/dtl/CONTRIBUTORS
  thirdparty/dtl/COPYING
  thirdparty/dtl/dtl/Diff.hpp
  thirdparty/dtl/dtl/Diff3.hpp
  thirdparty/dtl/dtl/Lcs.hpp
  thirdparty/dtl/dtl/Sequence.hpp
  thirdparty/dtl/dtl/Ses.hpp
  thirdparty/dtl/dtl/dtl.hpp
  thirdparty/dtl/dtl/functors.hpp
  thirdparty/dtl/dtl/variables.hpp
Labels: review

#3980 fix #231711: Tempo, staff text and other text honored in skipped volta
  libmscore/rendermidi.cpp
  libmscore/score.h
  libmscore/volta.cpp
  libmscore/volta.h
  mscore/exportmidi.cpp
  mtest/libmscore/midi/testVoltaDynamic-ref.mid
  mtest/libmscore/midi/testVoltaDynamic.mscx
  mtest/libmscore/midi/testVoltaStaffText-ref.mid
  mtest/libmscore/midi/testVoltaStaffText.mscx
  mtest/libmscore/midi/testVoltaTemp-ref.mid
  mtest/libmscore/midi/testVoltaTemp.mscx
  mtest/libmscore/midi/tst_midi.cpp
Labels: Priority, Test needed, review

#3957 fix #274925: Unable to select text in Chord Symbol
  libmscore/harmony.cpp
  libmscore/harmony.h
  libmscore/textbase.h
Labels: review

#3562 fix #270496: Add missing elements to incomplete tuplets when reading …
  libmscore/tuplet.cpp
  libmscore/tuplet.h
  libmscore/xmlreader.cpp
Labels: Priority, Test needed

#3548 Fix note collisions for 3.0
  libmscore/rendermidi.cpp
  libmscore/score.h
  mscore/exportmidi.cpp
  mscore/seq.cpp
  mtest/libmscore/midi/testAndanteExcerpts-ref.txt
  mtest/libmscore/midi/testKantataBWV140Excerpts-ref.txt
  mtest/libmscore/midi/tst_midi.cpp
  synthesizer/event.cpp
  synthesizer/event.h
Labels: Priority, review

#4133 fix #173381, part 1: handle selection after MMRest reconstruction
  libmscore/paste.cpp
  libmscore/select.cpp
  libmscore/select.h
  mtest/testscript/scripts/#173381-mmrest-repeat-1.mscx
  mtest/testscript/scripts/#173381-mmrest-repeat-1.script
  mtest/testscript/scripts/#173381-mmrest-repeat-2.mscx
  mtest/testscript/scripts/#173381-mmrest-repeat-2.script
  mtest/testscript/scripts/repeat-sel-end-score.mscx
  mtest/testscript/scripts/repeat-sel-end-score.script
Labels: review

#4134 fix #173381, part 2: assign correct duration to the pasted rests
  libmscore/paste.cpp
  mtest/testscript/scripts/#173381-mmrest-copy.mscx
  mtest/testscript/scripts/#173381-mmrest-copy.script
Labels: review

#4123 fix #277693: Fix melisma intersecting with lyrics syllables
  libmscore/line.cpp
  libmscore/lyricsline.cpp
Labels: work in progress

#4127 fix #277912: select/more for rests broken
  libmscore/score.cpp
  mscore/selectdialog.cpp
Labels: review

#4146 fix #111096: minor edits
  mscore/palette.cpp
Labels: review

#4115 fix #275813: handle linked parts in cmdJoinMeasure
  libmscore/joinMeasure.cpp
Labels: Test needed, review

#4113 fix #277864: Exchange voice does not add rests to complete voice 1
  libmscore/edit.cpp
  mtest/libmscore/exchangevoices/exchangevoices-gliss-ref.mscx
Labels: review

#4086 fix #277565: Shortening notes too much leads to bad stem layout
  fonts/mscore/mscore.otf
  fonts/mscore/mscore.sfd
  fonts/mscore/mscore.ttf
  libmscore/chord.cpp
Labels: Test needed, review

#4128 fix #277230 - MuseScore saves a corrupted file after importing a Musi…
  libmscore/fraction.cpp
  mtest/musicxml/io/testFractionMinus.xml
  mtest/musicxml/io/testFractionMinus_ref.xml
  mtest/musicxml/io/testFractionPlus.xml
  mtest/musicxml/io/testFractionPlus_ref.xml
  mtest/musicxml/io/testFractionTicks.xml
  mtest/musicxml/io/testFractionTicks_ref.xml
  mtest/musicxml/io/tst_mxml_io.cpp
Labels: work in progress

#3968 fix #275706: Place all articulations at stem side if direction and anchor is set to automatic
  libmscore/articulation.cpp
  libmscore/chord.cpp
  mtest/libmscore/compat206/articulations-double-ref.mscx
  mtest/libmscore/compat206/articulations-ref.mscx
  mtest/libmscore/implode_explode/undoExplode01-ref.mscx
  mtest/libmscore/parts/voices-ref.mscx
Labels: review
