Repository musescore/MuseScore, pull requests merged in 2019-05, with the labels that each got.

#4954 fix #116771: Note's dot's visibility is incorrect when toggling visibility with note and dot selected
  libmscore/cmd.cpp
Labels: Bugfix, review

#4935 Fixes to various aspects of stafftype
  libmscore/measure.cpp
  libmscore/staff.cpp
  libmscore/staff.h
  libmscore/stafftypechange.cpp
  libmscore/stafftypelist.h
  mscore/palette.cpp
Labels: review

#4910 fix #287622: scale spanners on paste special
  libmscore/paste.cpp
Labels: Bugfix, review

#4730 Autoplace user customization
  libmscore/articulation.cpp
  libmscore/beam.cpp
  libmscore/chord.cpp
  libmscore/chordrest.cpp
  libmscore/cmd.cpp
  libmscore/dynamic.cpp
  libmscore/element.cpp
  libmscore/element.h
  libmscore/fingering.cpp
  libmscore/fret.cpp
  libmscore/hairpin.cpp
  libmscore/jump.cpp
  libmscore/keysig.cpp
  libmscore/layout.cpp
  libmscore/layoutlinear.cpp
  libmscore/letring.cpp
  libmscore/marker.cpp
  libmscore/measure.cpp
  libmscore/mscore.cpp
  libmscore/mscore.h
  libmscore/ottava.cpp
  libmscore/palmmute.cpp
  libmscore/pedal.cpp
  libmscore/rest.cpp
  libmscore/score.h
  libmscore/segment.cpp
  libmscore/slur.cpp
  libmscore/spanner.cpp
  libmscore/spanner.h
  libmscore/style.cpp
  libmscore/style.h
  libmscore/textline.cpp
  libmscore/timesig.cpp
  libmscore/trill.cpp
  libmscore/vibrato.cpp
  libmscore/volta.cpp
  mscore/data/shortcuts.xml
  mscore/inspector/inspectorElementBase.cpp
  mscore/inspector/inspectorGroupElement.cpp
  mscore/inspector/inspectorGroupElement.h
  mscore/inspector/inspector_group_element.ui
  mscore/musescore.cpp
  mscore/shortcut.cpp
Labels: Improvement, review

#4866 fix #287120, fix #282503: incomplete filling of system
  libmscore/layout.cpp
Labels: review

#4767 Fix #283063: "MuseScore File" string (under File -> Save As...) does not indicate which version you are about to save as
  mscore/file.cpp
Labels: Suggestion, under discussion

#4928 fix #285174, fix #287283: add opengl32sw.dll as a (last) fallback
  mscore/CMakeLists.txt
Labels: Priority

#4070 Update AppData
  CMakeLists.txt
  build/Linux+BSD/org.musescore.MuseScore.appdata.xml.in
Labels: Improvement, review

#4785 Fret diagrams refactor
  .gitignore
  libmscore/fret.cpp
  libmscore/fret.h
  libmscore/property.cpp
  libmscore/property.h
  libmscore/style.cpp
  libmscore/style.h
  libmscore/undo.cpp
  libmscore/undo.h
  mscore/fretcanvas.h
  mscore/fretproperties.cpp
  mscore/importgtp-gp6.cpp
  mscore/importgtp.cpp
  mscore/importmxmlpass2.cpp
  mscore/inspector/inspectorFret.cpp
  mscore/inspector/inspectorFret.h
  mscore/inspector/inspector_fret.ui
  mscore/plugin/api/elements.h
  mtest/libmscore/selectionfilter/selectionfilter11-base-ref.xml
  mtest/libmscore/selectionfilter/updateReference
Labels: Bugfix

#4856 fix #286001: Change dynamicStyleFont to Italic
  libmscore/read206.cpp
  mtest/libmscore/compat206/accidentals-ref.mscx
  mtest/libmscore/compat206/ambitus-ref.mscx
  mtest/libmscore/compat206/articulations-double-ref.mscx
  mtest/libmscore/compat206/articulations-ref.mscx
  mtest/libmscore/compat206/barlines-ref.mscx
  mtest/libmscore/compat206/breath-ref.mscx
  mtest/libmscore/compat206/clefs-ref.mscx
  mtest/libmscore/compat206/drumset-ref.mscx
  mtest/libmscore/compat206/fermata-ref.mscx
  mtest/libmscore/compat206/hairpin-ref.mscx
  mtest/libmscore/compat206/intrumentNameAlign-ref.mscx
  mtest/libmscore/compat206/markers-ref.mscx
  mtest/libmscore/compat206/noteheads-ref.mscx
  mtest/libmscore/compat206/tuplets-ref.mscx
  mtest/libmscore/split/split183846-irregular-hn-hn-qn-qn-hn-hn-ref.mscx
  mtest/libmscore/split/split183846-irregular-qn-qn-wn-ref.mscx
  mtest/libmscore/split/split183846-irregular-verylong-ref.mscx
  mtest/libmscore/split/split183846-irregular-wn-wn-ref.mscx
  mtest/libmscore/split/split183846-irregular-wn-wr-wn-hr-qr-ref.mscx
  mtest/libmscore/split/split183846-irregular-wr-wn-wr-hn-qn-ref.mscx
Labels: Bugfix, review

#5022 fix #289250: Tabbing in edit mode leaves hairpin
  mscore/events.cpp
Labels: Bugfix, review

#5025 fix #289241: hairpin above won't stay in staff
  libmscore/hairpin.cpp
Labels: Priority

#5012 Fix #288348 - improved Play Panel layout (more compact)
  mscore/playpanel.cpp
  mscore/playpanel.ui
Labels: Improvement, Priority, review

#5030 Scale offsets with staff
  libmscore/chord.cpp
  libmscore/chord.h
  libmscore/chordrest.cpp
  libmscore/chordrest.h
  libmscore/note.cpp
  libmscore/note.h
  libmscore/rest.cpp
  libmscore/rest.h
  libmscore/staff.cpp
  libmscore/tremolo.cpp
Labels: Priority

#5032 fix #289211: bad layout of lyrics dashes at end of system
  libmscore/lyrics.h
  libmscore/lyricsline.cpp
  libmscore/spanner.cpp
Labels: Bugfix, Priority, review

#5034 fix #287397: unable to select bottom staves in single page view
  libmscore/layout.cpp
Labels: Priority

#5026 fix #289286: figured bass properties and autoplace
  libmscore/figuredbass.cpp
  libmscore/figuredbass.h
  libmscore/layout.cpp
  libmscore/style.cpp
  libmscore/style.h
Labels: Priority

#5035 fix #285680: single note dynamics not visible in MIDI output files
  libmscore/rendermidi.cpp
  mtest/libmscore/midi/testSingleNoteDynamics-ref.mid
Labels: Bugfix, Priority, review

#5011 Fix #287528 - Side panels not dockable after undock and close
  mscore/inspector/inspector.cpp
  mscore/menus.cpp
  mscore/mixer.cpp
  mscore/mixer.h
  mscore/mixer.ui
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/selectionwindow.cpp
  mscore/timeline.cpp
Labels: Bugfix, Priority, review

#5029 add chord symbol support for fret diagrams and some small read/write fixes
  libmscore/edit.cpp
  libmscore/fret.cpp
  libmscore/fret.h
  libmscore/harmony.cpp
  libmscore/property.cpp
  libmscore/property.h
  libmscore/style.cpp
  libmscore/style.h
  mscore/editharmony.cpp
  mscore/editstyle.cpp
  mscore/editstyle.ui
  mscore/inspector/inspectorFret.cpp
  mscore/inspector/inspector_fret.ui
  mscore/menus.cpp
  mscore/palette.cpp
  mscore/scoreview.cpp
  mtest/libmscore/compat206/accidentals-ref.mscx
  mtest/libmscore/compat206/ambitus-ref.mscx
  mtest/libmscore/compat206/articulations-double-ref.mscx
  mtest/libmscore/compat206/articulations-ref.mscx
  mtest/libmscore/compat206/barlines-ref.mscx
  mtest/libmscore/compat206/breath-ref.mscx
  mtest/libmscore/compat206/clefs-ref.mscx
  mtest/libmscore/compat206/drumset-ref.mscx
  mtest/libmscore/compat206/fermata-ref.mscx
  mtest/libmscore/compat206/hairpin-ref.mscx
  mtest/libmscore/compat206/intrumentNameAlign-ref.mscx
  mtest/libmscore/compat206/lidemptytext-ref.mscx
  mtest/libmscore/compat206/markers-ref.mscx
  mtest/libmscore/compat206/noteheads-ref.mscx
  mtest/libmscore/compat206/tuplets-ref.mscx
  mtest/libmscore/split/split183846-irregular-hn-hn-qn-qn-hn-hn-ref.mscx
  mtest/libmscore/split/split183846-irregular-qn-qn-wn-ref.mscx
  mtest/libmscore/split/split183846-irregular-verylong-ref.mscx
  mtest/libmscore/split/split183846-irregular-wn-wn-ref.mscx
  mtest/libmscore/split/split183846-irregular-wn-wr-wn-hr-qr-ref.mscx
  mtest/libmscore/split/split183846-irregular-wr-wn-wr-hn-qn-ref.mscx
  share/workspaces/Advanced.xml
Labels: Priority

#5027 fix #289293: articulation min distance not written
  libmscore/articulation.cpp
Labels: Priority
