Repository musescore/MuseScore, pull requests merged in 2019-08, with the labels that each got.

#5240 fix #284287: tab order in dialogs
  mscore/editstaff.ui
  mscore/editstafftype.ui
  mscore/editstyle.ui
  mscore/excerptsdialog.ui
  mscore/prefsdialog.ui
  mscore/selectdialog.ui
  mscore/selectnotedialog.ui
  mscore/transposedialog.ui
  mscore/uploadscoredialog.ui
Labels: Bugfix, RNIB, review

#5223 fix #287871: volta line not drawn before start repeat
  libmscore/line.cpp
Labels: Bugfix

#5093 fix #290136: add 'Style...' to property menu for all possible elements
  mscore/editstyle.cpp
  mscore/editstyle.h
  mscore/propertymenu.cpp
Labels: Improvement, review

#5227 281592 musicxml trill export
  libmscore/score.h
  libmscore/utils.cpp
  mscore/exportxml.cpp
  mscore/importmxmlpass2.cpp
  mscore/importmxmlpass2.h
  mtest/musicxml/io/testBarStyles3.xml
  mtest/musicxml/io/testLines1.pdf
  mtest/musicxml/io/testLines1.xml
  mtest/musicxml/io/tst_mxml_io.cpp
Labels: Bugfix, review

#4803 fix #285479: Implement scrolling a screen at a time in page view
  mscore/data/shortcuts.xml
  mscore/data/shortcuts_AZERTY.xml
  mscore/scoreview.cpp
  mscore/scoreview.h
  mscore/shortcut.cpp
Labels: Improvement, review

#5263 fix #147031: Note symbols are truncated in Tab Preview
  mscore/editstafftype.ui
  mscore/exampleview.cpp
Labels: Bugfix, review

#5166 fix #291292: Add 3/2 time signature to advanced workspace and master palette
  mscore/menus.cpp
  share/workspaces/Advanced.xml
  share/workspaces/Basic.xml
Labels: Improvement, review

#4950 fix #279828 - MusicXML import - attempting to fix badly read triplets…
  mscore/exportxml.cpp
  mscore/importmxmlnoteduration.cpp
  mscore/importmxmlnoteduration.h
  mscore/importmxmlpass1.cpp
  mscore/importmxmlpass1.h
  mscore/importmxmlpass2.cpp
  mscore/importmxmlpass2.h
  mtest/musicxml/io/testTuplets6.xml
  mtest/musicxml/io/testTuplets6_ref.xml
  mtest/musicxml/io/testTuplets7.xml
  mtest/musicxml/io/tst_mxml_io.cpp
Labels: Bugfix, review

#5150 fix #291079: "Save online" fails as of Qt 5.12.4 on Windows
  build/appveyor/before_build.bat
  mscore/CMakeLists.txt
Labels: Infrastructure, review

#5271 Fix #293464: Slash style for staff type change: Inspector label and function are not the same
  libmscore/chord.cpp
  libmscore/chordrest.cpp
  libmscore/layout.cpp
  libmscore/measure.cpp
  libmscore/measure.h
  libmscore/property.cpp
  libmscore/property.h
  libmscore/read114.cpp
  libmscore/read206.cpp
  libmscore/staff.cpp
  libmscore/staff.h
  libmscore/stafftype.cpp
  libmscore/stafftype.h
  libmscore/stafftypechange.cpp
  libmscore/tuplet.cpp
  libmscore/undo.cpp
  libmscore/undo.h
  mscore/editstafftype.cpp
  mscore/exportxml.cpp
  mscore/inspector/inspector.cpp
  mscore/inspector/inspector_stafftypechange.ui
  mscore/measureproperties.cpp
  mscore/measureproperties.h
  mscore/plugin/api/elements.h
Labels: Bugfix, review

#3461 allow unicode flat and sharp as input for chord symbols
  libmscore/harmony.cpp
Labels: work in progress

#5258 Fix #293008: Plugin: Provide Note.tieBack & Note.tieForward properties in QML.
  libmscore/note.h
  mscore/CMakeLists.txt
  mscore/plugin/api/elements.h
  mscore/plugin/api/qmlpluginapi.cpp
  mscore/plugin/api/tie.cpp
  mscore/plugin/api/tie.h
  mtest/CMakeLists.txt
Labels: Plugins

#5242 fix #282165: Mute voice produces note that doesn't stop when overlap present
  mscore/exportmidi.cpp
  mscore/seq.cpp
  mtest/libmscore/midi/testMutedUnison-ref.mid
  mtest/libmscore/midi/testMutedUnison.mscx
  mtest/libmscore/midi/tst_midi.cpp
  synthesizer/event.cpp
  synthesizer/event.h
Labels: Bugfix, review

#5277 fix #291932: Copy-paste breaths & pauses causes bad layout of the first note/rest in following measures
  libmscore/paste.cpp
Labels: Bugfix, Priority, review

#4545 compile fix for new portmidi versions
  mscore/CMakeLists.txt
Labels: review

#4878 fix #287245: allow symbols on barlines
  libmscore/barline.cpp
  libmscore/barline.h
  vtest/gen
  vtest/gen.bat
  vtest/symbol-1.mscx
  vtest/symbol-1.png
Labels: Improvement, Suggestion, review

#4846 fix #38941: multiple texts on mmrests
  libmscore/layout.cpp
Labels: Bugfix, review

#5139 Fix #288600 -R Command Line
  mscore/musescore.cpp
Labels: review

#5246 expansion of chord symbol formatting
  fonts/README.md
  fonts/campania/Campania.otf
  fonts/campania/LICENSE
  libmscore/chordlist.cpp
  libmscore/chordlist.h
  libmscore/harmony.cpp
  libmscore/harmony.h
  libmscore/mscore.cpp
  libmscore/property.cpp
  libmscore/property.h
  libmscore/style.cpp
  libmscore/style.h
  libmscore/types.h
  libmscore/undo.cpp
  mscore/CMakeLists.txt
  mscore/editharmony.cpp
  mscore/editstyle.cpp
  mscore/editstyle.ui
  mscore/exportxml.cpp
  mscore/importmxmlpass2.cpp
  mscore/musescore.cpp
  mscore/musescorefonts-Campania.qrc
  mscore/scoreview.cpp
  mscore/scoreview.h
  mscore/shortcut.cpp
  share/styles/chords_jazz.xml
  share/styles/chords_std.xml
  vtest/gen
  vtest/gen.bat
  vtest/harmony-13-ref.png
  vtest/harmony-13.mscx
  vtest/harmony-14-ref.png
  vtest/harmony-14.mscx
Labels: Improvement

#4957 fix #288169, #287889: draw lines when there are two hooks and draw hooks solid
  libmscore/textlinebase.cpp
  libmscore/textlinebase.h
  vtest/line-dashed-ref.png
  vtest/line-dashed.mscx
Labels: Test needed
