Repository musescore/MuseScore, pull requests merged in 2019-04, with the labels that each got.

#4609 Update playpanel
  mscore/playpanel.cpp
  mscore/playpanel.h
  mscore/playpanel.ui
Labels: Improvement, review, work in progress

#4807 Fix the look of Fine and To Coda in master repeats palette
  mscore/menus.cpp
Labels: Bugfix, review

#4858 fix #286530: scaling of dot, lines, and more in parts
  libmscore/excerpt.cpp
  libmscore/note.cpp
  libmscore/score.cpp
Labels: Bugfix, review

#4747 fix #279417: Add brackets after HBox with *Create system header*
  libmscore/bracket.h
  libmscore/layout.cpp
  libmscore/system.cpp
  libmscore/system.h
Labels: Bugfix, review, work in progress

#4754 fix #283168: Added read/writeProperty for HBox createSystemHeader
  libmscore/box.cpp
  libmscore/box.h
Labels: Bugfix, review, work in progress

#4847 Fix #284080: incorrectly listed beats
  libmscore/sig.cpp
  libmscore/sig.h
  mscore/scoreaccessibility.cpp
Labels: Bugfix, review

#4682 fix #282184 dont layout invisible slurs
  libmscore/layout.cpp
  libmscore/tie.cpp
Labels: Bugfix, review, work in progress
