Repository musescore/MuseScore, pull requests merged in 2019-03, with the labels that each got.

#4722 Fixes for system distances, margins, and spacers
  libmscore/layout.cpp
  libmscore/system.cpp
  libmscore/system.h
  mscore/scoreview.cpp
Labels: Bugfix, review

#4709 fix #284345, fix #281127: interpretation of grand staff distance
  libmscore/system.cpp
Labels: Bugfix

#4720 fix #282234: last bar of volta breaks mmrest
  libmscore/layout.cpp
  mtest/libmscore/measure/mmrest-ref.mscx
  mtest/libmscore/measure/mmrest.mscx
  mtest/libmscore/measure/tst_measure.cpp
Labels: Bugfix, review

#4743 fix #285100: Crash when moving beam if first note of beam is in the first measure and other notes of beam are in the second measure
  libmscore/layout.cpp
Labels: Bugfix, Test needed, review

#4742 fix #280878: by adding vector empty check in function Ms::Segment::nextAnnotation(Ms::Element * e).
  libmscore/segment.cpp
Labels: Bugfix, review

#4652 fix #283546: removing text frame causes second corrupt one to appear
  libmscore/score.cpp
Labels: Bugfix, review

#4631 fix #283179: Add some objects and properties to plugin api
  mscore/CMakeLists.txt
  mscore/plugin/api/elements.h
  mscore/plugin/api/excerpt.cpp
  mscore/plugin/api/excerpt.h
  mscore/plugin/api/part.h
  mscore/plugin/api/qmlpluginapi.cpp
  mscore/plugin/api/score.h
  mscore/plugin/api/scoreelement.cpp
  mscore/plugin/api/scoreelement.h
  mtest/CMakeLists.txt
Labels: review

#4726 fix #281957 beam property highlighting for selected notes
  mscore/events.cpp
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/palette.cpp
Labels: Bugfix, review, work in progress

#4665 fix #283946: play whole chord when iterating over notes
  mscore/prefsdialog.ui
  mscore/scoreview.cpp
Labels: Priority, review

#4537 Add start repeat
  demos/Unclaimed_Gift.mscx
Labels: Improvement, review

#4664 fix #283851: File path and name in score properties in unselectable and can't be copied to clipboard
  mscore/metaedit.cpp
  mscore/metaedit.ui
Labels: Improvement

#4708 Update_Timeline_Tempo
  mscore/timeline.cpp
Labels: review, work in progress

#4727 fix #284788 Fix keyboard navigation in single page view
  mscore/scoreview.cpp
Labels: Bugfix, review, work in progress

#4748 fix #284069: lyrics lines are respaced during export parts
  mscore/file.cpp
Labels: Bugfix, review, under discussion

#4752 fix #282698: undoing timesig change with tremolo causes crash
  libmscore/chord.cpp
  libmscore/edit.cpp
  libmscore/undo.cpp
  libmscore/undo.h
  mtest/libmscore/timesig/timesig-06-ref.mscx
  mtest/libmscore/timesig/timesig-06.mscx
  mtest/libmscore/timesig/timesig-07-ref.mscx
  mtest/libmscore/timesig/timesig-07.mscx
  mtest/libmscore/timesig/tst_timesig.cpp
  mtest/libmscore/timesig/updateReference
Labels: Test needed, review

#4574 fix #281652: cloneMeasure breaks tuplets
  libmscore/measure.cpp
Labels: Bugfix, review, work in progress

#4636 Fix warning stringop-truncate
  mscore/jackaudio.cpp
Labels: Improvement, review, work in progress

#4538 fix #68456: fixes pitch bends
  fluid/chan.cpp
  libmscore/rendermidi.cpp
  mscore/exportmidi.cpp
  mscore/seq.cpp
  mtest/libmscore/midi/testArpeggio-ref.mid
  mtest/libmscore/midi/testBends1-ref.mid
  mtest/libmscore/midi/testBends2-ref.mid
  mtest/libmscore/midi/testInitialKeySigThenRepeatToMeas2-ref.mid
  mtest/libmscore/midi/testRepeatsWithKeySigs-ref.mid
  mtest/libmscore/midi/testRepeatsWithKeySigsExceptFirstMeas-ref.mid
  mtest/libmscore/midi/testSingleNoteDynamics-ref.mid
  mtest/libmscore/midi/testTimeStretchFermata-ref.mid
  mtest/libmscore/midi/testVoltaDynamic-ref.mid
  mtest/libmscore/midi/testVoltaStaffText-ref.mid
  mtest/libmscore/midi/testVoltaTemp-ref.mid
  synthesizer/event.cpp
  synthesizer/event.h
Labels: Bugfix, review, work in progress

#4667 fix travis ci readme badge
  README.md
Labels: review

#4677 fix MSVC compiler warnings
  .appveyor.yml
  CMakeLists.txt
  libmscore/dynamic.cpp
  libmscore/hairpin.cpp
  libmscore/layout.cpp
  libmscore/midimapping.cpp
  libmscore/rendermidi.cpp
  libmscore/score.cpp
  mscore/file.cpp
  mscore/importgtp.cpp
  mscore/seq.cpp
Labels: Improvement, review, work in progress

#4769 fix #281024: invisible staves affect spacing
  libmscore/measure.cpp
  libmscore/segment.cpp
  libmscore/segment.h
Labels: Bugfix

#4253 fix #278847: two decimal places for tempo in inspector
  mscore/inspector/inspector_tempotext.ui
Labels: Improvement, review, work in progress

#4786 fix #283545: fix a crash on undoing HBox removal, fix boxes linking in parts
  libmscore/edit.cpp
  libmscore/score.cpp
  mtest/libmscore/chordsymbol/no-system-ref.mscx
Labels: Bugfix

#4773 fix #279259: chord symbol spacing
  libmscore/chordrest.cpp
  libmscore/harmony.cpp
  libmscore/harmony.h
  libmscore/segment.cpp
  libmscore/textedit.cpp
  vtest/harmony-1-ref.png
  vtest/harmony-1.mscx
Labels: Improvement, review

#4627 fix #282862: Moving an image can't be undone
  libmscore/image.cpp
  libmscore/image.h
Labels: Bugfix, review, work in progress

#4804 FIX#88411 tablature tie position
  libmscore/tie.cpp
Labels: Bugfix, review

#4792 fix #285781: loading existing scores no longer applies default style, loading parts no longer inherits style from parent
  libmscore/read206.cpp
  libmscore/read301.cpp
  libmscore/score.cpp
  mscore/file.cpp
  mscore/musescore.cpp
Labels: Bugfix, review

#4815 Fix various memory leaks on loading/closing score
  libmscore/beam.h
  libmscore/chordrest.cpp
  libmscore/chordrest.h
  libmscore/duration.cpp
  libmscore/duration.h
  libmscore/imageStore.cpp
  libmscore/imageStore.h
  libmscore/instrument.cpp
  libmscore/instrument.h
  libmscore/range.cpp
  libmscore/read206.cpp
  libmscore/score.cpp
  libmscore/scorefile.cpp
  libmscore/segment.cpp
  libmscore/spannermap.h
  libmscore/tuplet.cpp
  libmscore/tuplet.h
Labels: Improvement, Priority, review

#4611 fix #279389: rename timewise delete/input
  mscore/musescore.cpp
  mscore/scoreview.cpp
  mscore/shortcut.cpp
Labels: review, under discussion

#4265 fix #277903: new manpage
  build/Linux+BSD/mscore.1.in
  build/Linux+BSD/mscore.1.preview.sh
Labels: review

#4644 Tool to unroll all repeats. Fix #283592
  libmscore/CMakeLists.txt
  libmscore/cleflist.cpp
  libmscore/cleflist.h
  libmscore/excerpt.cpp
  libmscore/excerpt.h
  libmscore/key.h
  libmscore/measure.cpp
  libmscore/measure.h
  libmscore/score.cpp
  libmscore/score.h
  libmscore/staff.cpp
  libmscore/staff.h
  libmscore/timesig.h
  libmscore/unrollrepeats.cpp
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/shortcut.cpp
  mtest/CMakeLists.txt
  mtest/libmscore/unrollrepeats/CMakeLists.txt
  mtest/libmscore/unrollrepeats/clef-key-ts-ref.mscx
  mtest/libmscore/unrollrepeats/clef-key-ts-test.mscx
  mtest/libmscore/unrollrepeats/pickup-measure-ref.mscx
  mtest/libmscore/unrollrepeats/pickup-measure-test.mscx
  mtest/libmscore/unrollrepeats/tst_unrollrepeats.cpp
Labels: Improvement, Priority, review

#4829 vtest for invisible staff spacing
  vtest/gen
  vtest/gen.bat
  vtest/layout-9-ref-1.png
  vtest/layout-9.mscx
Labels: review
