Repository musescore/MuseScore, pull requests merged in 2019-11, with the labels that each got.

#5413 Add the bbox property to PluginAPI::Element
  mscore/plugin/api/elements.cpp
  mscore/plugin/api/elements.h
Labels: Plugins

#5200 [WIP] AppImage: improve build scripts
  .travis.yml
  Makefile
  build/Linux+BSD/portable/AppRun.in
  build/Linux+BSD/portable/Recipe
  build/Linux+BSD/portable/x86_64/Dockerfile
  build/Linux+BSD/portable/x86_64/Recipe
  build/travis/job2_AppImage/bintray.sh
  build/travis/job2_AppImage/build.sh
  mscore/CMakeLists.txt
Labels: work in progress

#4263 Fix #279024: double click on mixer's dial and sliders should reset th…
  mscore/mixertrackpart.cpp
Labels: under discussion

#5397 fix #292474: Ambitus crash in plugins
  mscore/plugin/api/cursor.cpp
  mscore/plugin/api/elements.cpp
  mscore/plugin/api/elements.h
Labels: Plugins
