Repository musescore/MuseScore, pull requests merged in 2019-02, with the labels that each got.

#4416 fix #279671 - MusicXML export loses tablature info, produces unrecogn…
  mscore/exportxml.cpp
Labels: review

#4604 fix #282249: guitar vibratos play earlier than they should after repeated measures
  libmscore/rendermidi.cpp
  mtest/libmscore/midi/testGuitarTrem-ref.txt
  mtest/libmscore/midi/testGuitarTrem.mscx
  mtest/libmscore/midi/tst_midi.cpp
Labels: review

#4520 fix #280900 Implode Single Measure
  libmscore/cmd.cpp
Labels: review

#4648 log vtest comparison in machine-parsable format
  vtest/gen
Labels: review

#4596 fix #281910 ottava import 2.x
  libmscore/read206.cpp
Labels: review, under discussion

#4451 fix #280338: Changed fullscreen state to ~STATE_TEXT_EDIT
  mscore/shortcut.cpp
Labels: Priority, review

#3595 fix #270990: Unable to add fermatas to bar lines
  libmscore/barline.cpp
  libmscore/edit.cpp
  libmscore/layout.cpp
  libmscore/measure.cpp
  libmscore/read114.cpp
  libmscore/read206.cpp
  libmscore/read206.h
Labels: Priority

#3965 fix #276217 Support MIDI-IN while playback engaged
  mscore/pianotools.cpp
  mscore/pianotools.h
  mscore/preferences.cpp
  mscore/preferences.h
  mscore/scoreview.cpp
  mscore/seq.cpp
Labels: Priority, review

#4641 fix #278767: Always position dragged item to the top left of the cursor
  mscore/palette.cpp
Labels: review, work in progress

#3694 fix #272887: Unable to add mid-measure clef on the first tick of a measure
  libmscore/clef.cpp
  libmscore/cmd.cpp
  libmscore/edit.cpp
  libmscore/keysig.cpp
  libmscore/measure.cpp
  libmscore/score.cpp
  libmscore/score.h
  libmscore/staff.cpp
  mtest/libmscore/clef_courtesy/tst_clef_courtesy.cpp
Labels: Priority

#4626 remove superfluous/duplicate channels
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: review

#4544 fix #57056: content of status bar doesn't get deleted if last score gets closed
  mscore/events.cpp
  mscore/inspector/inspector.cpp
  mscore/musescore.cpp
  mscore/scoreaccessibility.cpp
Labels: review
