Repository musescore/MuseScore, pull requests merged in 2019-01, with the labels that each got.

#4507 fix #280422: align hairpin and dynamics
  libmscore/hairpin.cpp
  libmscore/layout.cpp
Labels: Priority, review

#3962 fix #276194 Allow MIDI devices to be refreshed without having to restart MuseScore
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/pa.cpp
  mscore/prefsdialog.cpp
  mscore/prefsdialog.h
  mscore/prefsdialog.ui
Labels: Priority, review

#4200 Accessibility: New Score Wizard
  mscore/CMakeLists.txt
  mscore/newwizard.cpp
  mscore/newwizard.h
  mscore/newwizard.ui
  mscore/palette.cpp
  mscore/scorePreview.cpp
  mscore/scorePreview.h
  mscore/scorePreview.ui
  mscore/templateBrowser.cpp
  mscore/templateBrowser.h
  mscore/templateBrowser.ui
  mscore/timesigwizard.ui
  mscore/widgets/CMakeLists.txt
  mscore/widgets/README.md
  mscore/widgets/filterabletreeview.cpp
  mscore/widgets/filterabletreeview.h
  mscore/widgets/filterableview.h
  mscore/widgets/searchbox.cpp
  mscore/widgets/searchbox.h
Labels: RNIB, review

#4511 fix #280714: copy excerpts list before removing excerpts in a loop
  mscore/instrdialog.cpp
Labels: Priority, review

#4515 fix #280547 tuplet brackets connected to two staves
  libmscore/tuplet.cpp
  mtest/libmscore/tuplet/nestedTuplets_addStaff-ref.mscx
  mtest/libmscore/tuplet/nestedTuplets_addStaff.mscx
  mtest/libmscore/tuplet/tst_tuplet.cpp
Labels: Priority, review

#4524 fix #280830 exit edit mode if double-click palette
  mscore/palette.cpp
Labels: Priority, review

#4543 InstrumentsWidget: Replace TreeWidget with FilterableTreeWidget
  mscore/instrwidget.cpp
  mscore/instrwidget.h
  mscore/instrwidget.ui
  mscore/selectinstr.ui
  mscore/selinstrument.cpp
  mscore/selinstrument.h
  mscore/widgets/CMakeLists.txt
  mscore/widgets/filterabletreeview.cpp
  mscore/widgets/filterabletreeview.h
  mscore/widgets/filterableview.cpp
  mscore/widgets/filterableview.h
Labels: RNIB, review

#4540 Make Start Center child of MuseScore's Main Window
  mscore/startcenter.cpp
  mscore/startcenter.h
Labels: review, under discussion

#4527 replacing "..." (3 dots) with "…" (ellipsis)
  fluid/fluidgui.cpp
  libmscore/dynamic.cpp
  libmscore/textbase.cpp
  mscore/albummanager.ui
  mscore/downloadUtils.cpp
  mscore/editdrumset.ui
  mscore/editstaff.ui
  mscore/editstringdata.ui
  mscore/editstyle.cpp
  mscore/editstyle.ui
  mscore/exportaudio.cpp
  mscore/fotomode.cpp
  mscore/harmonyedit.ui
  mscore/importmidi/importmidi_lyrics.cpp
  mscore/importmidi/importmidi_model.cpp
  mscore/instrdialog.ui
  mscore/loginmanager.cpp
  mscore/musescore.cpp
  mscore/palette.cpp
  mscore/palette.ui
  mscore/paletteBoxButton.cpp
  mscore/pluginCreator.cpp
  mscore/pluginCreator.ui
  mscore/prefsdialog.ui
  mscore/propertymenu.cpp
  mscore/scoreBrowser.cpp
  mscore/scoreview.cpp
  mscore/shortcut.cpp
  mscore/startcenter.ui
  mscore/updatechecker.cpp
  mscore/workspace.cpp
  omr/omr.cpp
  zerberus/zerberusgui.cpp
Labels: review, under discussion

#4552 fix #280631: fix writing offset and length for pedal lines
  libmscore/pedal.cpp
  mtest/libmscore/compat114/pedal-ref.mscx
Labels: review

#4491 fix #280632: Add shaker, fix tubo instrument
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: review

#4525 MSVC pch allow switch configuration
  build/CreatePrecompiledHeader.cmake
Labels: review

#4487 fix #151256: fix lyrics intersection inside measure, disallow lyrics to cross barlines
  libmscore/measure.cpp
  libmscore/measure.h
  libmscore/segment.cpp
  libmscore/segmentlist.cpp
  libmscore/segmentlist.h
  libmscore/shape.cpp
Labels: Priority, review

#4492 various text fixes
  effects/compressor/compressor_gui.ui
  libmscore/clef.cpp
  libmscore/keysig.cpp
  libmscore/pitchspelling.cpp
  mscore/editraster.ui
  mscore/exportmp3.cpp
  mscore/inspector/inspector_ottava.ui
  mscore/menus.cpp
  mscore/musescore.cpp
  mscore/musicxmlsupport.cpp
  mscore/parteditbase.cpp
  mscore/prefsdialog.cpp
  mscore/prefsdialog.ui
  mscore/shortcut.cpp
  mscore/templateBrowser.cpp
  mscore/updatechecker.cpp
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
  share/tours/inspector.tour
  share/tours/noteinput.tour
  share/tours/tourxml.h
  share/tours/welcome.tour
  share/workspaces/Advanced.workspace
  share/workspaces/Basic.workspace
Labels: Priority, review

#4528 fix #280523: Switch size changes with staff space settings does not affect styles individually
  libmscore/read206.cpp
  libmscore/style.cpp
  libmscore/style.h
Labels: Priority, review

#4533 fix #281154: Crash with first note of measure set to beam middle and nothing to beam to
  libmscore/layout.cpp
Labels: Priority, review

#4582 fix #281761: Adding interval to note in parts leads to crash
  libmscore/cmd.cpp
Labels: Priority

#4603 Ensure workspaces are always compressed after being modified
  CMakeLists.txt
  build/container.xml.in
  build/functions.cmake
  share/workspaces/Advanced.xml
  share/workspaces/Advanced/META-INF/container.xml
  share/workspaces/Basic.xml
  share/workspaces/Basic/META-INF/container.xml
  share/workspaces/CMakeLists.txt
Labels: review

#4608 "About MuseScore" dialog strings adjustments to meet MStore requirements
  mscore/musescore.cpp
Labels: review

#4613 fix #280613: Color not available as a text style setting
  libmscore/style.cpp
  libmscore/style.h
  mscore/editstyle.cpp
  mscore/editstyle.ui
Labels: review

#4617 follow up pr #4535: display patches in mixer in order of preset numbe…
  aeolus/aeolus.cpp
  fluid/fluid.cpp
  mscore/mixerdetails.cpp
  synthesizer/midipatch.h
  zerberus/zerberus.cpp
Labels: review

#4623 Replace login dialog with login webView from musescore.com
  mscore/CMakeLists.txt
  mscore/logindialog.cpp
  mscore/logindialog.h
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/network/loginmanager.cpp
  mscore/network/loginmanager.h
  mscore/network/loginmanager_p.h
  mscore/uploadscoredialog.cpp
  mscore/uploadscoredialog.h
Labels: review
