Repository musescore/MuseScore, pull requests merged in 2020-05, with the labels that each got.

#5808 fix #278988 Copy and paste notes in Piano Roll Editor
  global/settings/types/preferencekeys.h
  libmscore/note.cpp
  libmscore/note.h
  mscore/musescore.cpp
  mscore/pianoroll/pianolevelschooser.ui
  mscore/pianoroll/pianoroll.cpp
  mscore/pianoroll/pianoview.cpp
  mscore/pianoroll/pianoview.h
  mscore/preferences.cpp
Labels: Strings

#5744 fix #299644: add support for fret diagram rotation
  libmscore/fret.cpp
  libmscore/fret.h
  libmscore/harmony.cpp
  libmscore/harmony.h
  libmscore/property.cpp
  libmscore/property.h
  libmscore/style.cpp
  libmscore/style.h
  mscore/inspector/inspectorFret.cpp
  mscore/inspector/inspector_fret.ui
  vtest/gen-ref
  vtest/harmony-2-ref.png
  vtest/layout-sequence-10-ref.png
  vtest/layout-sequence-14-ref.png
  vtest/layout-sequence-16-ref.png
Labels: Strings, work in progress

#5760 fix #301584: test for duplicates names in palette
  libmscore/arpeggio.cpp
  libmscore/arpeggio.h
  libmscore/barline.cpp
  libmscore/glissando.cpp
  libmscore/glissando.h
  libmscore/sym.cpp
  mscore/menus.cpp
  mtest/CMakeLists.txt
  mtest/mscore/palette/CMakeLists.txt
  mtest/mscore/palette/tst_palette.cpp
  mtest/mtest.cpp
  share/workspaces/Advanced.xml
  share/workspaces/Basic.xml
Labels: review

#6063 fix 305130: misleading shortcut descriptions
  mscore/shortcut.cpp
Labels: Strings

#6061 Fix #305123: Add (Concert) Cimbalom
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: Strings

#6093 Fix #279773 - Articulations are duplicated on adding linked staves, c…
  libmscore/excerpt.cpp
  mscore/instrdialog.cpp
Labels: review

#6077 fix some translatable strings
  mscore/metaedit.cpp
  mscore/musescore.cpp
  mscore/partedit.ui
  mscore/pianoroll/pianoroll.cpp
  mscore/scoreaccessibility.cpp
Labels: Strings

#6052 Fix #277796: Inconsistent octave selection in note input mode
  libmscore/cmd.cpp
  mtest/testscript/scripts/note-input-octave.mscx
  mtest/testscript/scripts/note-input-octave.script
Labels: Test needed, review
