Repository musescore/MuseScore, pull requests merged in 2020-04, with the labels that each got.

#3163 Clean up some temp files after they are not needed anymore
  libmscore/scorefile.cpp
  mscore/exportaudio.cpp
  mscore/fotomode.cpp
  mscore/musescore.cpp
  mscore/uploadscoredialog.cpp
Labels: Priority

#5621 Simplify version-specific configuration in build scripts
  CMakeLists.txt
  Makefile
  Makefile.mingw
  Makefile.osx
  build/appveyor/after_build.bat
  build/appveyor/before_build.bat
  build/appveyor/build_script.bat
  build/appveyor/winsparkle_appcast_generator.sh
  build/config/dev.cmake
  build/config/release.cmake
  build/config/testing.cmake
  build/package_mac
  build/travis/job1_Tests/run_tests.sh
  build/travis/job2_AppImage/build.sh
  build/travis/job_macos/before_install.sh
  build/travis/job_macos/script.sh
  build/travis/job_macos_lupdate/before_install.sh
  config.cmake
  msvc_build.bat
Labels: Infrastructure

#5456 [Backup File] fix #295701: able to open backup files as an import
  libmscore/scorefile.cpp
  mscore/file.cpp
Labels: Strings

#5612 Support "all lines attached to stem" beam style of tremolo (partially fix #18897)
  libmscore/property.cpp
  libmscore/property.h
  libmscore/style.cpp
  libmscore/style.h
  libmscore/tremolo.cpp
  libmscore/tremolo.h
  mscore/inspector/inspector.cpp
  mscore/inspector/inspector.h
  mscore/inspector/inspector_tremolo.ui
Labels: Improvement, Strings

#5619 More beautiful default layout related to tremolos (fix #20390) (+ collect_artifacts)
  libmscore/chord.cpp
  libmscore/layout.cpp
  libmscore/tremolo.cpp
  libmscore/tremolo.h
  vtest/grace-4-ref.png
  vtest/tremolo-1-ref.png
Labels: Improvement

#5633 Add support for deleting (custom) metatags.
  mscore/data/icons/bin.svg
  mscore/icons.cpp
  mscore/icons.h
  mscore/metaedit.cpp
  mscore/metaedit.h
  mscore/metaedit.ui
  mscore/musescore.qrc
Labels: Strings

#5332 fix #294542: Allow setting notehead scheme on a note-by-note basis in the Inspector
  libmscore/mscore.h
  libmscore/note.cpp
  libmscore/note.h
  libmscore/property.cpp
  libmscore/property.h
  libmscore/stafftype.cpp
  libmscore/stafftype.h
  libmscore/stafftypechange.cpp
  mscore/editstafftype.cpp
  mscore/inspector/inspector.cpp
  mscore/inspector/inspectorNote.cpp
  mscore/inspector/inspectorNote.h
  mscore/inspector/inspector_note.ui
  mscore/plugin/api/elements.h
  mscore/plugin/api/qmlpluginapi.cpp
  mscore/plugin/api/qmlpluginapi.h
Labels: Improvement

#5921 Change to MSVC 2019
  .appveyor.yml
  CMakeLists.txt
  CMakeSettings.json
Labels: review

#5738 Rework anchor lines drawing
  libmscore/arpeggio.cpp
  libmscore/arpeggio.h
  libmscore/articulation.cpp
  libmscore/articulation.h
  libmscore/bsymbol.cpp
  libmscore/bsymbol.h
  libmscore/element.cpp
  libmscore/element.h
  libmscore/fermata.cpp
  libmscore/fermata.h
  libmscore/fret.cpp
  libmscore/fret.h
  libmscore/hairpin.h
  libmscore/image.h
  libmscore/line.cpp
  libmscore/line.h
  libmscore/score.cpp
  libmscore/slurtie.cpp
  libmscore/slurtie.h
  libmscore/textbase.cpp
  libmscore/textbase.h
  mscore/dragdrop.cpp
  mscore/dragelement.cpp
  mscore/editelement.cpp
  mscore/scoreview.cpp
  mscore/scoreview.h
Labels: work in progress

#5643 Fix a crash on MSCZ reading, add a way of handling such errors
  libmscore/measure.cpp
  libmscore/read301.cpp
  libmscore/score.h
  mscore/file.cpp
Labels: Strings

#5763 Rebase segment-anchored lines on dragging
  libmscore/CMakeLists.txt
  libmscore/beam.cpp
  libmscore/box.cpp
  libmscore/dynamic.cpp
  libmscore/dynamic.h
  libmscore/dynamichairpingroup.cpp
  libmscore/dynamichairpingroup.h
  libmscore/element.cpp
  libmscore/element.h
  libmscore/elementgroup.cpp
  libmscore/elementgroup.h
  libmscore/hairpin.cpp
  libmscore/hairpin.h
  libmscore/line.cpp
  libmscore/line.h
  libmscore/measure.cpp
  libmscore/measure.h
  libmscore/note.cpp
  libmscore/score.cpp
  libmscore/score.h
  libmscore/segment.cpp
  libmscore/segment.h
  libmscore/spanner.cpp
  libmscore/system.cpp
  libmscore/system.h
  libmscore/utils.cpp
  mscore/dragelement.cpp
  mscore/editelement.cpp
  mscore/scoreview.cpp
  mscore/scoreview.h
Labels: work in progress

#5919 fix #302822: breaks are now accessible via keyboard
  libmscore/navigate.cpp
  libmscore/segment.cpp
Labels: review

#5371 fix #294085: all elements set to normal position if all rests in voices other than voice 1 are deleted
  libmscore/beam.cpp
  libmscore/beam.h
  libmscore/chord.cpp
  libmscore/fingering.cpp
  libmscore/layout.cpp
  libmscore/measure.cpp
  libmscore/measure.h
  libmscore/rest.cpp
  libmscore/slur.cpp
  libmscore/tie.cpp
Labels: under discussion

#5814 Piano Roll Editor Keyboard Zoom
  mscore/data/shortcuts-Mac.xml
  mscore/data/shortcuts.xml
  mscore/data/shortcuts_AZERTY.xml
  mscore/globals.h
  mscore/pianoroll/pianoroll.cpp
  mscore/pianoroll/pianoroll.h
  mscore/pianoroll/pianoview.cpp
  mscore/pianoroll/pianoview.h
  mscore/shortcut.cpp
Labels: Strings

#5644 fix #300172: problems with bass clarinet
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: Strings

#5630 fix #279210: cannot change properties of multiple notes in piano roll editor
  mscore/pianoroll/pianoroll.cpp
Labels: review

#5884 fix #303078: Fixed a bug where the cursor would be on the wrong height after deleting all chars in a line
  libmscore/textbase.cpp
  libmscore/textbase.h
  libmscore/textedit.cpp
Labels: review

#5657 Plugin API: alter Cursor API for better usage in interactive plugins
  libmscore/noteentry.cpp
  libmscore/score.h
  mscore/musescore.cpp
  mscore/plugin/api/cursor.cpp
  mscore/plugin/api/cursor.h
  mscore/plugin/api/qmlpluginapi.h
  mscore/shortcut.cpp
  mscore/shortcut.h
  share/plugins/notenames-interactive.qml
Labels: Plugins, Suggestion

#5646 Add reveal in finder (show in explorer) option in metaedit dialog.
  mscore/CMakeLists.txt
  mscore/metaedit.cpp
  mscore/metaedit.h
  mscore/metaedit.ui
  mscore/openfilelocation.cpp
  mscore/openfilelocation.h
Labels: Strings

#4798 Add channel switch staff texts for SATB Closed Score and Barbershop
  mscore/menus.cpp
  share/workspaces/Advanced.xml
Labels: Suggestion, under discussion

#4916 fix #287662: transpose keys
  libmscore/keysig.cpp
  libmscore/transpose.cpp
Labels: Bugfix, review

#5970 Fix #303902: Export to SVG with trim via command line results in blank image
  mscore/file.cpp
Labels: review

#5715 fix #239181: make fret diagrams accessible for screenreaders
  libmscore/fret.cpp
  libmscore/fret.h
  libmscore/harmony.cpp
  libmscore/harmony.h
  mscore/scoreaccessibility.cpp
Labels: Strings
