Repository musescore/MuseScore, pull requests merged in 2020-03, with the labels that each got.

#5778 fix #283111: Add octobass
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: Strings

#5790 follow up fix for Barbershop-Women template
  share/instruments/instrumentsxml.h
  share/templates/CMakeLists.txt
  share/templates/convert.json
Labels: Strings

#5764 fix #301656: add "Baritone Horn (Central Europe)"
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: Strings

#5759 fix #301600: Option to disable the pop-up "Reset the positions of all elements?"
  global/settings/types/preferencekeys.h
  mscore/musescore.cpp
  mscore/preferences.cpp
  mscore/prefsdialog.cpp
  mscore/prefsdialog.ui
Labels: Strings

#5727 Fix #301124: Always show correct pathname in Score Properties
  mscore/metaedit.cpp
Labels: Strings

#5474 fix #297040: Palette keyboard navigation
  mscore/palette/palettemodel.cpp
  mscore/qml/palettes/Palette.qml
  mscore/qml/palettes/PaletteTree.qml
  mscore/qml/palettes/PalettesWidget.qml
  mscore/qml/palettes/PalettesWidgetHeader.qml
  mscore/qml/palettes/TreePaletteHeader.qml
Labels: RNIB, Strings

#5363 Accessibility: Note input toolbutton
  mscore/musescore.cpp
  mscore/toolbuttonmenu.cpp
  mscore/toolbuttonmenu.h
Labels: Improvement, RNIB

#5655 add accessible names & labels
  mscore/inspector/inspector_element.ui
  mscore/inspector/inspector_note.ui
  mscore/inspector/offset_select.ui
Labels: RNIB, Strings

#3877 Removing " Look in: styles" when not appropriate
  mscore/file.cpp
Labels: under discussion

#4147 fix #278080: Request to show empty page rather than no page for score with no content
  libmscore/layout.cpp
Labels: Suggestion, under discussion

#4468 fix #279859 reallow drop break elements on vbox
  libmscore/box.cpp
Labels: under discussion

#5000 fix some compiler warnings differently/cleaner
  fluid/voice.cpp
  libmscore/cmd.cpp
  libmscore/dynamic.h
  libmscore/edit.cpp
  libmscore/glissando.cpp
  libmscore/layout.cpp
  libmscore/location.cpp
  libmscore/measure.cpp
  libmscore/midimapping.cpp
  libmscore/note.cpp
  libmscore/pitchspelling.cpp
  libmscore/rendermidi.cpp
  libmscore/scorediff.cpp
  libmscore/select.cpp
  libmscore/staff.cpp
  libmscore/stafftype.cpp
  libmscore/sym.cpp
  libmscore/tremolo.h
  libmscore/xmlreader.cpp
  mscore/editstyle.cpp
  mscore/events.cpp
  mscore/fretcanvas.cpp
  mscore/importmidi/importmidi_beat.cpp
  mscore/importmidi/importmidi_lrhand.cpp
  mscore/importmidi/importmidi_quant.cpp
  mscore/importmidi/importmidi_tuplet.cpp
  mscore/importmidi/importmidi_tuplet_filter.cpp
  mscore/importmidi/importmidi_tuplet_voice.cpp
  mscore/importmidi/importmidi_voice.cpp
  mscore/importmxmlpass1.cpp
  mscore/importmxmlpass2.cpp
  mscore/importove.cpp
  mscore/inspector/inspectorAmbitus.cpp
  mscore/mixer.cpp
  mscore/mixertrackitem.cpp
  mscore/ove.cpp
  mscore/pianolevels.cpp
  mscore/pianolevelsfilter.cpp
  mscore/pianoroll.cpp
  mscore/pianoview.cpp
  mscore/plugin/api/cursor.cpp
  mscore/plugin/qmledit.cpp
  mscore/scorecmp/scorelistmodel.cpp
  mscore/script/scriptentry.cpp
  mscore/seq.cpp
  mscore/tourhandler.cpp
Labels: review

#5608 Improve error message from flip command
  libmscore/edit.cpp
  libmscore/mscore.cpp
  libmscore/mscore.h
Labels: Strings

#5500 fix #288495: allow user to select flats or sharps for enharmonic key signatures
  libmscore/edit.cpp
  libmscore/key.cpp
  libmscore/key.h
  libmscore/part.cpp
  libmscore/part.h
  libmscore/property.cpp
  libmscore/property.h
  libmscore/score.cpp
  libmscore/transpose.cpp
  mscore/editstaff.cpp
  mscore/editstaff.h
  mscore/editstaff.ui
  mscore/file.cpp
  mscore/instrdialog.cpp
  mscore/musescore.cpp
  mscore/palette.cpp
  mscore/timeline.cpp
  mtest/libmscore/keysig/preferSharpFlat-1-ref.mscx
  mtest/libmscore/keysig/preferSharpFlat-1.mscx
  mtest/libmscore/keysig/preferSharpFlat-2-ref.mscx
  mtest/libmscore/keysig/preferSharpFlat-2.mscx
  mtest/libmscore/keysig/tst_keysig.cpp
Labels: Strings

#5010 Fix #289006: Expose "Select Instrument" in Inspector for Instrument Change text
  mscore/inspector/inspector.cpp
  mscore/inspector/inspector.h
  mscore/inspector/inspectorInstrchange.cpp
  mscore/inspector/inspectorInstrchange.h
  mscore/inspector/inspector_instrchange.ui
  mscore/propertymenu.cpp
  mscore/scoreview.h
Labels: Strings

#5833 Tiny string fix
  mscore/editstaff.ui
Labels: Strings

#5617 fix #299727: Change Transpose "By Key" to "To Key"
  libmscore/mscore.h
  libmscore/transpose.cpp
  mscore/file.cpp
  mscore/musescore.cpp
  mscore/transposedialog.cpp
  mscore/transposedialog.h
  mscore/transposedialog.ui
Labels: Strings

#5832 fix some (translatable) texts
  avsomr/ret.cpp
  avsomr/ui/recognitionproccessdialog.cpp
  mscore/inspector/inspector_instrchange.ui
Labels: Strings

#5782 [GSoC 2019] Instrument change improvements
  libmscore/chordrest.cpp
  libmscore/clef.cpp
  libmscore/clef.h
  libmscore/edit.cpp
  libmscore/element.h
  libmscore/instrchange.cpp
  libmscore/instrchange.h
  libmscore/instrument.cpp
  libmscore/instrument.h
  libmscore/key.cpp
  libmscore/key.h
  libmscore/keysig.cpp
  libmscore/keysig.h
  libmscore/score.h
  libmscore/textbase.cpp
  libmscore/textbase.h
  libmscore/transpose.cpp
  mscore/dragdrop.cpp
  mscore/palette.cpp
  mscore/propertymenu.cpp
Labels: Strings

#5836 Fixed crash on Measure write (from CrashReporter)
  libmscore/measure.cpp
Labels: Bugfix

#5445 fix #292606: image attached to a measure doesn't show
  libmscore/measure.cpp
  libmscore/read114.cpp
  libmscore/read206.cpp
  mscore/dragdrop.cpp
Labels: Bugfix

#5830 Fixed crash fluids voice noteoff (from CrashReporter)
  mscore/seq.cpp
  mscore/seq.h
Labels: Bugfix
