Repository musescore/MuseScore, pull requests merged in 2020-01, with the labels that each got.

#5626 Plugin API: merge changes from onScoreStateChanged with user action in undo stack
  libmscore/score.cpp
  libmscore/score.h
  mscore/musescore.cpp
  mscore/musescore.h
  mscore/plugin/api/score.cpp
  mscore/plugin/api/score.h
  mscore/plugin/qmlpluginengine.cpp
  mscore/plugin/qmlpluginengine.h
Labels: Plugins

#5639 [Regression] fix #300107: crash after closing a menu bar pop-up window if no score is loaded
  mscore/plugin/qmlpluginengine.cpp
Labels: Priority

#5658 fix #300347: capital "L" cannot be entered in text
  mscore/shortcut.cpp
Labels: Bugfix
