Repository musescore/MuseScore, pull requests merged in 2020-02, with the labels that each got.

#5618 Use separate version number to decide whether to show telemetry dialog
  mscore/musescore.cpp
Labels: under discussion

#5627 fix #299387: support for more screen readers
  mscore/musescore.cpp
  mscore/scoreaccessibility.cpp
  mscore/scoreaccessibility.h
  mscore/scoretab.cpp
  mscore/scoreview.cpp
Labels: RNIB

#5622 Pocket Sax improvements
  share/instruments/instruments.xml
  share/instruments/instrumentsxml.h
Labels: Strings

#5471 fix #23187 - [MusicXML] Layout exports despite being disabled in Preferences
  mscore/exportxml.cpp
  mscore/prefsdialog.cpp
  mscore/prefsdialog.ui
Labels: Strings

#5737 fix #301387: add Wyschnegradsky accidentals
  libmscore/accidental.cpp
  libmscore/sym.cpp
  libmscore/types.h
Labels: Strings
