Repository musescore/MuseScore, pull requests merged in 2022-09, with the labels that each got.

#13156 Fix the `maxChordShiftAbove` and `maxChordShiftBelow` style settings
  src/engraving/layout/layoutoptions.h
  src/engraving/layout/layoutsystem.cpp
Labels: vtests

#13134 Fix #11645: Draw bar lines and clefs in cutaway situations
  src/engraving/libmscore/measure.cpp
  src/engraving/libmscore/segment.cpp
  vtest/scores/cutaway.mscz
Labels: vtests

#13029 Stem slash redesign
  src/engraving/layout/layoutmeasure.cpp
  src/engraving/libmscore/beam.cpp
  src/engraving/libmscore/stemslash.cpp
  src/engraving/libmscore/stemslash.h
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  vtest/scores/stemSlash-1-bravura.mscz
  vtest/scores/stemSlash-1-gonville.mscz
  vtest/scores/stemSlash-1-maestro.mscz
  vtest/scores/stemSlash-1.mscz
  vtest/scores/stemSlash-2-bravura.mscz
  vtest/scores/stemSlash-2-gonville.mscz
  vtest/scores/stemSlash-2-maestro.mscz
  vtest/scores/stemSlash-2.mscz
  vtest/scores/stemSlash-3.mscz
Labels: vtests

#13101 A definitive solution to cross-beam spacing (also Fix #13120)
  src/engraving/layout/layoutsystem.cpp
  src/engraving/layout/layoutsystem.h
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/measure.cpp
  src/engraving/libmscore/segment.cpp
  src/engraving/libmscore/segment.h
  src/engraving/libmscore/system.cpp
  src/engraving/libmscore/system.h
  vtest/scores/cross-5.mscz
Labels: vtests

#13188 Fix beam positions beside TAB staff
  src/engraving/libmscore/beam.cpp
  src/engraving/libmscore/beam.h
  src/engraving/libmscore/chord.cpp
  vtest/scores/tablature-beams-1.mscz
Labels: vtests

#13223 A few refinements and corrections on slurs
  src/engraving/libmscore/slur.cpp
  vtest/scores/slurs-15.mscz
Labels: vtests

#13254 Tweak some defaults
  share/templates/01-General/01-Treble_Clef/score_style.mss
  share/templates/01-General/02-Bass_Clef/score_style.mss
  share/templates/01-General/03-Grand_Staff/score_style.mss
  share/templates/02-Choral/01-SATB/score_style.mss
  share/templates/02-Choral/02-SATB_+_Organ/score_style.mss
  share/templates/02-Choral/03-SATB_+_Piano/score_style.mss
  share/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
  share/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
  share/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
  share/templates/02-Choral/07-Voice_+_Piano/score_style.mss
  share/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
  share/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
  share/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
  share/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
  share/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
  share/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
  share/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
  share/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
  share/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
  share/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
  share/templates/04-Solo/01-Guitar/score_style.mss
  share/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
  share/templates/04-Solo/03-Guitar_Tablature/score_style.mss
  share/templates/04-Solo/04-Piano/score_style.mss
  share/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
  share/templates/05-Jazz/02-Big_Band/score_style.mss
  share/templates/05-Jazz/03-Jazz_Combo/score_style.mss
  share/templates/06-Popular/01-Rock_Band/score_style.mss
  share/templates/06-Popular/02-Bluegrass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
  share/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
  share/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
  share/templates/08-Orchestral/03-String_Orchestra/score_style.mss
  src/engraving/libmscore/score.cpp
  src/engraving/style/styledef.cpp
Labels: vtests

#13270 Cutaway clefs correction
  src/engraving/libmscore/measure.cpp
  vtest/scores/cutaway.mscz
Labels: vtests

#13245 Fix stem slash glitch
  src/engraving/libmscore/engravingitem.h
  src/engraving/libmscore/shape.cpp
  src/engraving/libmscore/stemslash.cpp
  src/engraving/libmscore/stemslash.h
Labels: vtests

#13305 Slur over articulation refinement
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/slur.cpp
  src/engraving/libmscore/slur.h
  vtest/scores/slurs-16.mscz
Labels: vtests

#13333 Multiple voices overlaps with one dotted correction
  src/engraving/layout/layoutchords.cpp
  vtest/scores/chord-layout-19.mscz
Labels: vtests

#13371 [MU4] Apply chord magnitude to the vertical adjustment of slurs
  src/engraving/libmscore/slur.cpp
Labels: vtests

#13373 [MU4] Avoid applying magnitude twice for tie attach points
  src/engraving/libmscore/note.cpp
  src/engraving/libmscore/tie.cpp
Labels: vtests

#13370 Tweaked note spacing for overlapping unisons/seconds
  src/engraving/layout/layoutchords.cpp
Labels: vtests

#13308 Slur over grace notes refinement
  src/engraving/layout/layoutsystem.cpp
  src/engraving/libmscore/slur.cpp
  src/engraving/libmscore/slur.h
  vtest/scores/slurs-17.mscz
Labels: vtests

#13354 Note dot alignment correction
  src/engraving/layout/layoutchords.cpp
  src/engraving/layout/layoutchords.h
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/chord.h
  src/engraving/libmscore/segment.cpp
  src/engraving/libmscore/segment.h
  vtest/scores/chord-layout-20.mscz
Labels: vtests

#13407 Fix (repeat) barline bbox and layout if Sid::spatium ≉ SPATIUM20
  src/engraving/libmscore/barline.cpp
  src/engraving/libmscore/barline.h
Labels: vtests

#13265 Invisible time sig fix
  src/engraving/libmscore/segment.cpp
  vtest/scores/hideEmptyStaves.mscz
Labels: vtests

#13427 [MU4] Missed case on slur-tie adjustment
  src/engraving/libmscore/slur.cpp
  vtest/scores/slur-adjust-for-tie.mscz
Labels: vtests

#11536 Set default shortcuts for toggling accidentals and ties
  src/framework/shortcuts/data/shortcuts-Mac.xml
  src/framework/shortcuts/data/shortcuts.xml
  src/framework/shortcuts/data/shortcuts_AZERTY.xml
  src/notation/internal/notationuiactions.cpp
Labels: strings, P2

#13496 Style default tweaks
  share/templates/01-General/01-Treble_Clef/score_style.mss
  share/templates/01-General/02-Bass_Clef/score_style.mss
  share/templates/01-General/03-Grand_Staff/score_style.mss
  share/templates/02-Choral/01-SATB/score_style.mss
  share/templates/02-Choral/02-SATB_+_Organ/score_style.mss
  share/templates/02-Choral/03-SATB_+_Piano/score_style.mss
  share/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
  share/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
  share/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
  share/templates/02-Choral/07-Voice_+_Piano/score_style.mss
  share/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
  share/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
  share/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
  share/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
  share/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
  share/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
  share/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
  share/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
  share/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
  share/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
  share/templates/04-Solo/01-Guitar/score_style.mss
  share/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
  share/templates/04-Solo/03-Guitar_Tablature/score_style.mss
  share/templates/04-Solo/04-Piano/score_style.mss
  share/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
  share/templates/05-Jazz/02-Big_Band/score_style.mss
  share/templates/05-Jazz/03-Jazz_Combo/score_style.mss
  share/templates/06-Popular/01-Rock_Band/score_style.mss
  share/templates/06-Popular/02-Bluegrass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
  share/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
  share/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
  share/templates/08-Orchestral/03-String_Orchestra/score_style.mss
  src/engraving/style/styledef.cpp
Labels: vtests

#13523 Some translation tweaks
  share/locale/musescore_en.ts
  src/appshell/view/appmenumodel.cpp
  src/appshell/view/internal/splashscreen.cpp
  src/diagnostics/internal/diagnosticsactions.cpp
  src/engraving/types/typesconv.cpp
  src/notation/internal/notationuiactions.cpp
  src/notation/view/widgets/stafftextpropertiesdialog.ui
  src/playback/internal/playbackuiactions.cpp
  src/playback/qml/MuseScore/Playback/SoundProfilesDialog.qml
  src/project/internal/projectuiactions.cpp
Labels: strings

#13508 Gradual tempo change line improvements
  src/engraving/libmscore/gradualtempochange.cpp
  src/engraving/libmscore/gradualtempochange.h
  src/engraving/libmscore/line.cpp
  vtest/scores/stacking-order.mscz
  vtest/scores/tempoChangeLines.mscz
Labels: vtests

#13516 Fermata over bar rest correction
  src/engraving/libmscore/fermata.cpp
  vtest/scores/fermata-2.mscz
Labels: vtests

#13515 [MU4] Extend 3+ beams to middle line
  src/engraving/libmscore/beam.cpp
  src/engraving/libmscore/chord.cpp
  src/engraving/utests/beam_data/beamNoSlope.mscx
  src/engraving/utests/beam_data/beamPositions.mscx
  src/engraving/utests/beam_data/wideBeams.mscx
  vtest/scores/beams-middle-line.mscz
Labels: vtests

#12917 Rework languages module and fix updating language
  src/appshell/internal/appshellconfiguration.cpp
  src/appshell/qml/Preferences/GeneralPreferencesPage.qml
  src/appshell/qml/Preferences/internal/LanguagesSection.qml
  src/appshell/view/preferences/generalpreferencesmodel.cpp
  src/appshell/view/preferences/generalpreferencesmodel.h
  src/framework/global/types/retval.h
  src/languages/CMakeLists.txt
  src/languages/ilanguagesconfiguration.h
  src/languages/ilanguagesservice.h
  src/languages/ilanguageunpacker.h
  src/languages/internal/languagesconfiguration.cpp
  src/languages/internal/languagesconfiguration.h
  src/languages/internal/languagesservice.cpp
  src/languages/internal/languagesservice.h
  src/languages/internal/languageunpacker.cpp
  src/languages/internal/languageunpacker.h
  src/languages/languageserrors.h
  src/languages/languagesmodule.cpp
  src/languages/languagesmodule.h
  src/languages/languagestypes.h
Labels: strings
