Repository musescore/MuseScore, pull requests merged in 2023-10, with the labels that each got.

#19540 fix #19528 wrong keysig on next system after undo
  src/engraving/rendering/dev/measurelayout.cpp
  src/engraving/tests/transpose_data/undoTranspose02-ref.mscx
Labels: vtests

#19559 factor hook offset into stem slash calculations
  src/engraving/rendering/dev/tlayout.cpp
  vtest/scores/grace-hook-slash.mscz
Labels: vtests

#19558 factor notehead offset into stem length calculations
  src/engraving/dom/chord.cpp
  src/engraving/rendering/dev/beamtremololayout.cpp
  vtest/scores/notehead-offset.mscz
Labels: vtests

#19402 Ledger lines clear stems when voices overlap
  src/engraving/rendering/dev/chordlayout.cpp
  vtest/scores/flag-straight.mscz
  vtest/scores/flag.mscz
  vtest/scores/ledger-lines-2.mscz
  vtest/scores/ledger-lines-3.mscz
Labels: vtests

#19690 [engraving] Fixed Shape clear
  src/engraving/infrastructure/shape.h
Labels: vtests

#19703 Fix dynamics avoid bar line bug
  src/engraving/dom/dynamic.cpp
Labels: P1

#19707 Fix wrong offset value displayed in inspector when "Follow staff size" is disabled
  src/inspector/models/abstractinspectormodel.cpp
Labels: P2, UI

#19745 Relayout chord when direction changes
  src/engraving/rendering/dev/measurelayout.cpp
Labels: P2, engraving

#19403 Smarter gliss positioning around chord shapes
  src/engraving/rendering/dev/tlayout.cpp
  vtest/scores/gliss-5.mscz
  vtest/scores/symbol-2.mscz
Labels: vtests

#19296 Fixed tremolo placement on simple tab staff
  src/engraving/rendering/dev/tremololayout.cpp
  vtest/scores/tremolo-tab-2.mscx
Labels: vtests

#19161 Fix #17891: Instrument names follow largest stave spatium in part
  src/engraving/dom/instrumentname.cpp
  src/engraving/dom/instrumentname.h
  src/engraving/dom/textbase.cpp
  vtest/scores/instrument-names.mscz
Labels: vtests

#19659 Apply score changes immediately when importing <4.0
  src/engraving/dom/cmd.cpp
  src/engraving/dom/score.cpp
  src/engraving/dom/score.h
  src/engraving/rw/read114/read114.cpp
  src/engraving/rw/read206/read206.cpp
  src/engraving/rw/read400/measurerw.cpp
  src/engraving/rw/read400/tread.cpp
  src/engraving/tests/compat114_data/notes_useroffset-ref.mscx
  src/engraving/tests/compat206_data/fermata-ref.mscx
  src/engraving/tests/compat206_data/lidemptytext-ref.mscx
Labels: vtests

#19831 Enable 2nd adjustment for cross staff beamed notes
  src/engraving/rendering/dev/chordlayout.cpp
  vtest/scores/cross-8.mscz
Labels: vtests
