Repository musescore/MuseScore, pull requests merged in 2023-11, with the labels that each got.

#19948 Correct system width after right aligned segment
  src/engraving/rendering/dev/systemlayout.cpp
  vtest/scores/breath-2.mscz
Labels: vtests

#19666 Create defaults for pedal begin, continue and end text
  src/engraving/dom/pedal.cpp
  src/engraving/dom/textlinebase.cpp
  src/engraving/dom/textlinebase.h
  src/engraving/rw/read114/read114.cpp
  src/engraving/rw/read206/read206.cpp
  src/engraving/rw/read400/tread.cpp
  src/engraving/rw/read410/tread.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/tests/compat114_data/pedal-ref.mscx
  src/engraving/tests/compat206_data/textstyles-ref.mscx
  src/engraving/tests/selectionfilter_data/selectionfilter9-base-ref.xml
  src/importexport/mei/internal/meiconverter.cpp
  src/importexport/mei/tests/data/color-01.mscx
  src/importexport/mei/tests/data/pedal-01.mscx
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/inspector/models/notation/lines/pedalsettingsmodel.cpp
  src/inspector/models/notation/lines/pedalsettingsmodel.h
  src/palette/internal/palettecreator.cpp
  vtest/scores/pedal-2.mscz
  vtest/scores/pedal-3.mscz
Labels: vtests

#19828 Calculate rest vertical adjustment after cross staff stem layout
  src/engraving/dom/beam.cpp
  src/engraving/dom/beam.h
  src/engraving/infrastructure/shape.cpp
  src/engraving/infrastructure/shape.h
  src/engraving/rendering/dev/beamlayout.cpp
  src/engraving/rendering/dev/beamtremololayout.cpp
  src/engraving/rendering/dev/pagelayout.cpp
  src/engraving/rendering/dev/systemlayout.cpp
  vtest/scores/beams-25.mscz
Labels: vtests

#19605 Add import/export of invisible clefs to MusicXML
  src/importexport/musicxml/internal/musicxml/exportxml.cpp
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/importexport/musicxml/tests/data/testInvisibleElements.xml
Labels: MusicXML

#19294 "Double Coda" to "Doppia Coda"
  src/engraving/dom/jump.cpp
  src/engraving/dom/marker.cpp
  src/engraving/tests/repeat_tests.cpp
  src/engraving/types/typesconv.cpp
  src/importexport/guitarpro/internal/importgtp-gp5.cpp
  src/importexport/guitarpro/tests/data/directions.gp-ref.mscx
  src/importexport/guitarpro/tests/data/directions.gpx-ref.mscx
  src/importexport/mei/tests/data/jump-01.mei
  src/importexport/mei/tests/data/jump-01.mscx
  src/importexport/mei/tests/data/jump-02.mei
  src/importexport/mei/tests/data/jump-02.mscx
Labels: strings

#20069 Fix crash on alt+arrow navigation from grace note to preceding rest
  src/engraving/dom/chord.cpp
  src/engraving/dom/segment.cpp
Labels: crash

#20110 Layout bracket after creation
  src/engraving/rendering/dev/systemlayout.cpp
  vtest/scores/brackets-1.mscz
Labels: vtests

#20124 Use MiterJoin for drawing tuplet brackets
  src/engraving/rendering/dev/tdraw.cpp
Labels: vtests, engraving

#20161 More tie refinements
  src/engraving/dom/note.cpp
  src/engraving/dom/note.h
  src/engraving/dom/tie.cpp
  src/engraving/rendering/dev/slurtielayout.cpp
  src/engraving/rendering/dev/slurtielayout.h
  vtest/scores/tie-10.mscz
  vtest/scores/tie-11.mscz
  vtest/scores/tie-12.mscz
Labels: vtests

#20239 Correct tie position on slash notes
  src/engraving/rendering/dev/slurtielayout.cpp
  vtest/scores/tie-13.mscz
Labels: vtests
