Repository musescore/MuseScore, pull requests merged in 2023-07, with the labels that each got.

#18322 [4.1.0] Beam distance fix backport
  src/engraving/layout/v0/beamtremololayout.cpp
Labels: vtests

#18086 Fix rest vertical offset with invisible chords
  src/engraving/layout/v0/chordlayout.cpp
  src/engraving/libmscore/rest.cpp
  src/engraving/libmscore/shape.cpp
  src/engraving/libmscore/shape.h
  vtest/scores/rests-6.mscz
Labels: vtests

#18205 Fix #17994: Respect stem-articulation min distance inside staff
  src/engraving/layout/v0/chordlayout.cpp
  vtest/scores/articulation-beams-1.mscz
  vtest/scores/articulation-beams-2.mscz
Labels: vtests

#17269 Crescendo lines overlap + Chord text frame
  src/engraving/layout/v0/tlayout.cpp
  src/engraving/libmscore/textlinebase.cpp
  src/engraving/libmscore/textlinebase.h
  vtest/scores/hairpins-2.mscx
  vtest/scores/harmony-17.mscz
Labels: vtests

#18386 Port PRs from master
  src/engraving/layout/v0/chordlayout.cpp
  src/engraving/layout/v0/tlayout.cpp
  src/engraving/libmscore/edit.cpp
  src/engraving/libmscore/rest.cpp
  src/engraving/libmscore/shape.cpp
  src/engraving/libmscore/shape.h
  src/engraving/libmscore/textedit.cpp
  src/engraving/style/style.cpp
  src/engraving/style/style.h
  src/engraving/tests/clef_courtesy_data/clef_courtesy01-ref.mscx
  src/engraving/tests/clef_courtesy_data/clef_courtesy02-ref.mscx
  src/engraving/tests/clef_courtesy_data/clef_courtesy03-ref.mscx
  src/engraving/tests/clef_courtesy_data/clef_courtesy04-ref.mscx
  src/engraving/tests/measure_data/measure-10-ref.mscx
  src/engraving/tests/measure_data/measure-4-ref.mscx
  src/engraving/tests/measure_data/measure-5-ref.mscx
  src/engraving/tests/measure_data/measure-6-ref.mscx
  src/engraving/tests/measure_data/measure-7-ref.mscx
  src/engraving/tests/measure_data/measure-8-ref.mscx
  src/engraving/tests/measure_data/measure-9-ref.mscx
  src/inspector/models/notation/accidentals/accidentalsettingsmodel.cpp
  src/inspector/models/notation/accidentals/accidentalsettingsmodel.h
  src/inspector/view/qml/MuseScore/Inspector/notation/accidentals/AccidentalSettings.qml
  vtest/scores/grace-11.mscz
  vtest/scores/rests-6.mscz
Labels: vtests

#18411 Correct autoplace for expression when not snapping to dynamic
  src/engraving/layout/v0/tlayout.cpp
Labels: vtests

#17110 adjust midi bank and program for bandurria and laud
  share/instruments/instruments.xml
Labels: instruments

#18501 Fix expression snapping above staff
  src/engraving/layout/v0/tlayout.cpp
  src/engraving/libmscore/textbase.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/tests/compat206_data/textstyles-ref.mscx
  src/engraving/tests/expression_data/expression-1-ref.mscx
  vtest/scores/expression-2.mscz
Labels: vtests

#18581 crash_fixes
  src/braille/internal/louis.cpp
  src/engraving/layout/v0/tlayout.cpp
  src/engraving/libmscore/chordline.cpp
  src/engraving/libmscore/edit.cpp
  src/notation/inotationparts.h
  src/notation/internal/masternotation.cpp
  src/notation/internal/notationparts.cpp
  src/notation/internal/notationparts.h
  src/playback/internal/playbackcontroller.cpp
  src/playback/internal/playbackcontroller.h
Labels: P0

#18659 crash_fixes
  src/appshell/view/dockwindow/internal/dockbase.cpp
  src/framework/audio/internal/platform/win/wasapiaudiodriver.cpp
  src/framework/shortcuts/view/mididevicemappingmodel.cpp
  src/framework/uicomponents/view/popupwindow/popupwindow_qquickview.cpp
  src/multiinstances/internal/ipc/ipc.cpp
Labels: P0

#18596 Fixed crash when restoring mu navigation in app menu
  src/appshell/view/navigableappmenumodel.cpp
  src/appshell/view/navigableappmenumodel.h
  src/framework/ui/inavigationcontroller.h
  src/framework/ui/internal/navigationcontroller.cpp
  src/framework/ui/internal/navigationcontroller.h
Labels: P1

#18648 Potentially fix infinite loop in multi-measure repeat playback rendering
  src/engraving/libmscore/measure.cpp
  src/engraving/playback/playbackmodel.cpp
Labels: P0
