Repository musescore/MuseScore, pull requests merged in 2023-03, with the labels that each got.

#16602 Fix cross-staff beam direction when starting with rest
  src/engraving/layout/layoutbeams.cpp
  vtest/scores/beams-22.mscz
Labels: vtests

#15225 When avoiding a slur, move the entire articulations group
  src/engraving/libmscore/chord.cpp
  vtest/scores/articulation-5.mscz
Labels: vtests

#15809 Fix #15746: Repeat texts not outside voltas
  src/engraving/layout/layoutsystem.cpp
Labels: vtests

#16595 Fix cross staff ties bug
  src/engraving/libmscore/tie.cpp
  vtest/scores/tie-4.mscz
Labels: vtests

#16611 Grace note shapes should take into account staff moves
  src/engraving/layout/layoutchords.cpp
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/chord.h
  src/engraving/libmscore/segment.cpp
  src/engraving/libmscore/segment.h
  vtest/scores/grace-10.mscz
Labels: vtests

#16080 Fix system lines alignment on MMRests
  src/engraving/libmscore/line.cpp
  src/engraving/libmscore/spanner.cpp
  vtest/scores/mmrest-15.mscz
Labels: P1, engraving

#16159 Fix TAB alignment issue
  src/engraving/layout/layoutchords.cpp
  vtest/scores/tablature-2.mscz
Labels: vtests

#16616 Fix #13800: Take line distance into account in stem length calculation
  src/engraving/libmscore/chord.cpp
Labels: vtests

#15849 Fix #15779: Add rest section to properties panel
  fonts/mscore/MusescoreIcon.ttf
  src/framework/ui/view/iconcodes.h
  src/inspector/CMakeLists.txt
  src/inspector/internal/services/elementrepositoryservice.cpp
  src/inspector/internal/services/elementrepositoryservice.h
  src/inspector/models/abstractinspectormodel.cpp
  src/inspector/models/abstractinspectormodel.h
  src/inspector/models/inspectormodelcreator.cpp
  src/inspector/models/notation/beams/beammodesmodel.cpp
  src/inspector/models/notation/beams/beammodesmodel.h
  src/inspector/models/notation/notes/beams/beamsettingsmodel.h
  src/inspector/models/notation/rests/beams/restbeamsettingsmodel.cpp
  src/inspector/models/notation/rests/beams/restbeamsettingsmodel.h
  src/inspector/models/notation/rests/restsettingsproxymodel.cpp
  src/inspector/models/notation/rests/restsettingsproxymodel.h
  src/inspector/view/inspector_resources.qrc
  src/inspector/view/qml/MuseScore/Inspector/notation/NotationInspectorSectionLoader.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/beams/BeamTypeSelector.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/notes/BeamSettings.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/rests/RestBeamSettings.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/rests/RestSettings.qml
Labels: P2

#15822 Introducing text settings for tempo change
  src/engraving/libmscore/gradualtempochange.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/style/textstyle.cpp
  src/engraving/types/types.h
  src/engraving/types/typesconv.cpp
  src/importexport/musicxml/tests/data/testMeasureStyleSlash_ref.mscx
Labels: P1

#13312 [MU4] Straight flags now spaced better
  src/engraving/libmscore/chord.cpp
Labels: vtests, P2, engraving

#15370 Minimum tie length correction at start of system
  src/engraving/layout/layoutmeasure.cpp
  vtest/scores/minTieLength-1.mscz
Labels: P1, engraving

#16836 Small correction to Segment width offset
  src/engraving/libmscore/measure.cpp
Labels: vtests

#15613 Antialiase plugin thumbnails
  src/plugins/qml/MuseScore/Plugins/internal/PluginItem.qml
Labels: P3

#16292 Fix chord line scaling
  src/engraving/libmscore/chordline.cpp
  src/engraving/libmscore/chordline.h
  src/engraving/style/styledef.cpp
  vtest/scores/chordLine.mscz
Labels: vtests

#15778 Fix MMRest bug
  share/templates/01-General/01-Treble_Clef/score_style.mss
  share/templates/01-General/02-Bass_Clef/score_style.mss
  share/templates/01-General/03-Grand_Staff/score_style.mss
  share/templates/02-Choral/01-SATB/score_style.mss
  share/templates/02-Choral/02-SATB_+_Organ/score_style.mss
  share/templates/02-Choral/03-SATB_+_Piano/score_style.mss
  share/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
  share/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
  share/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
  share/templates/02-Choral/07-Voice_+_Piano/score_style.mss
  share/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
  share/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
  share/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
  share/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
  share/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
  share/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
  share/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
  share/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
  share/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
  share/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
  share/templates/04-Solo/01-Guitar/score_style.mss
  share/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
  share/templates/04-Solo/03-Guitar_Tablature/score_style.mss
  share/templates/04-Solo/04-Piano/score_style.mss
  share/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
  share/templates/05-Jazz/02-Big_Band/score_style.mss
  share/templates/05-Jazz/03-Jazz_Combo/score_style.mss
  share/templates/06-Popular/01-Rock_Band/score_style.mss
  share/templates/06-Popular/02-Bluegrass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
  share/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
  share/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
  share/templates/08-Orchestral/03-String_Orchestra/score_style.mss
  src/engraving/libmscore/measure.cpp
  src/engraving/libmscore/segment.cpp
  src/engraving/style/styledef.cpp
Labels: vtests

#15831 Correct cross-beam spacing in narrow situations
  src/engraving/libmscore/measure.cpp
  src/engraving/libmscore/segment.cpp
  src/engraving/libmscore/segment.h
Labels: vtests, P2, engraving

#16629 Fix #15939: Add special handling for stemless slash heads
  src/engraving/libmscore/note.cpp
  vtest/scores/whole-slash-tie-attach.mscz
Labels: vtests

#16880 Several corrections to rests with ledger lines
  src/engraving/libmscore/engravingitem.cpp
  src/engraving/libmscore/rest.cpp
  src/engraving/libmscore/rest.h
  vtest/scores/rests-4.mscz
Labels: vtests

#15531 Optimizations and code improvement
  src/engraving/layout/layoutsystem.cpp
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/engravingitem.cpp
  src/engraving/libmscore/lyricsline.cpp
  src/engraving/libmscore/note.cpp
  src/engraving/libmscore/rest.cpp
  src/engraving/libmscore/segment.cpp
  src/engraving/libmscore/shape.cpp
  src/engraving/libmscore/shape.h
  src/engraving/libmscore/slur.cpp
  vtest/scores/slurs-22.mscz
Labels: vtests

#16026 Several chord layout corrections
  src/engraving/layout/layoutchords.cpp
  src/engraving/libmscore/note.cpp
  vtest/scores/chord-layout-21.mscz
Labels: vtests

#16109 MMRest width correction
  src/engraving/libmscore/segment.cpp
Labels: vtests

#16719 A complete overhaul of rest positioning logic
  src/engraving/layout/layoutbeams.cpp
  src/engraving/layout/layoutbeams.h
  src/engraving/layout/layoutchords.cpp
  src/engraving/layout/layoutchords.h
  src/engraving/layout/layoutmeasure.cpp
  src/engraving/layout/layoutsystem.cpp
  src/engraving/libmscore/beam.cpp
  src/engraving/libmscore/beam.h
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/chordrest.cpp
  src/engraving/libmscore/chordrest.h
  src/engraving/libmscore/engravingobject.h
  src/engraving/libmscore/mmrest.cpp
  src/engraving/libmscore/rest.cpp
  src/engraving/libmscore/rest.h
  src/engraving/libmscore/score.cpp
  src/engraving/libmscore/shape.cpp
  src/engraving/libmscore/shape.h
  src/engraving/libmscore/utils.cpp
  src/engraving/libmscore/utils.h
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/tests/parts_data/part-image-parts.mscx
  src/engraving/tests/parts_data/part-image-udel.mscx
  src/engraving/tests/parts_data/part-image.mscx
  src/engraving/types/types.h
  src/engraving/types/typesconv.cpp
  src/importexport/ove/internal/importove.cpp
  src/notation/internal/notationinteraction.cpp
  src/notation/notationmodule.cpp
  src/notation/notationscene.qrc
  src/notation/qml/MuseScore/NotationScene/internal/EditStyle/RestOffsetSelector.qml
  src/notation/view/styledialog/restspagemodel.cpp
  src/notation/view/styledialog/restspagemodel.h
  src/notation/view/styledialog/styledialog.cmake
  src/notation/view/widgets/editstyle.cpp
  src/notation/view/widgets/editstyle.ui
  vtest/scores/beams-23.mscz
  vtest/scores/rests-1.mscz
  vtest/scores/rests-2.mscz
  vtest/scores/rests-3.mscz
  vtest/scores/slash-2.mscz
Labels: vtests

#16078 The clickable bounding box of a item should not necessarily coincide with the engraving bounding box
  src/engraving/libmscore/engravingitem.cpp
  src/engraving/libmscore/engravingitem.h
  src/engraving/libmscore/stafflines.cpp
  src/engraving/libmscore/stafflines.h
  src/notation/internal/notationinteraction.cpp
  vtest/scores/articulation-6.mscz
Labels: vtests

#12547 [MU4] Improve the dot adjustment algorithm
  src/engraving/libmscore/note.cpp
  src/engraving/libmscore/note.h
  vtest/scores/chord-layout-dots.mscz
Labels: vtests, P1, engraving

#16972 Fingering vs articulation
  src/engraving/layout/layoutchords.cpp
  src/engraving/layout/layoutchords.h
  src/engraving/layout/layoutsystem.cpp
  vtest/scores/fingeringVSarticulation.mscz
Labels: vtests

#16999 fixed infinite loop during layout for small page sizes
  src/engraving/layout/layoutsystem.cpp
Labels: vtests
