Repository musescore/MuseScore, pull requests merged in 2023-05, with the labels that each got.

#13807 Reimplement "zoom to page width" command
  src/notation/internal/notationuiactions.cpp
Labels: strings

#17437 dynamics correction
  src/engraving/libmscore/textbase.cpp
Labels: vtests

#17303 Various articulation improvements
  src/engraving/libmscore/articulation.cpp
  src/engraving/libmscore/articulation.h
  src/engraving/libmscore/chord.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/notation/internal/notationinteraction.cpp
Labels: vtests

#16967 Fix #15638: Ignore hidden names on first system
  src/engraving/libmscore/system.cpp
  src/engraving/libmscore/system.h
Labels: vtests

#12863 [MU4] Add single stroke caesura
  src/engraving/libmscore/breath.cpp
  src/engraving/types/symnames.cpp
  src/importexport/braille/internal/exportbraille.cpp
  src/palette/internal/palettecreator.cpp
  tools/fonttools/smufl2sym-in-trans.json
Labels: strings

#10000 [MU4] Fix #306189: Extend Tremolo palette
  src/engraving/libmscore/articulation.cpp
  src/engraving/types/symnames.cpp
  src/palette/internal/palettecreator.cpp
  tools/fonttools/smufl2sym-in-trans.json
Labels: strings

#10282 [MU4] Fix #328451: Add 2 (baroque) trills
  src/engraving/libmscore/articulation.cpp
  src/engraving/libmscore/rendermidi.cpp
  src/engraving/playback/metaparsers/internal/symbolsmetaparser.cpp
  src/engraving/types/symnames.cpp
  src/importexport/musicxml/internal/musicxml/exportxml.cpp
  src/palette/internal/palettecreator.cpp
  tools/fonttools/smufl2sym-in-trans.json
Labels: strings

#16636 Fix #16317: Added tied, cross bar chords handling.
  src/engraving/libmscore/cmd.cpp
  src/engraving/libmscore/edit.cpp
  src/engraving/libmscore/noteentry.cpp
  src/engraving/libmscore/score.h
Labels: P1, community, engraving

#10412 Add 2 Couperin ornaments
  src/engraving/libmscore/articulation.cpp
  src/engraving/libmscore/rendermidi.cpp
  src/engraving/playback/metaparsers/internal/symbolsmetaparser.cpp
  src/engraving/types/symnames.cpp
  src/importexport/musicxml/internal/musicxml/exportxml.cpp
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/palette/internal/palettecreator.cpp
  tools/fonttools/smufl2sym-in-trans.json
Labels: strings

#17520 Enhance tuplet direction detection based on voices
  src/engraving/layout/tupletlayout.cpp
  vtest/scores/empty-tuplets.mscz
Labels: vtests

#17028 Fix #15327: Apply 1/8sp inset regardless of manual adjustment
  src/engraving/layout/slurtielayout.cpp
  src/engraving/libmscore/tie.cpp
Labels: vtests

#17640 Consolidate staff/chord anchors into trinary above/below/auto
  src/engraving/layout/v0/chordlayout.cpp
  src/engraving/libmscore/articulation.cpp
  src/engraving/libmscore/articulation.h
  src/engraving/libmscore/chord.cpp
  src/engraving/libmscore/edit.cpp
  src/engraving/rw/206/read206.cpp
  src/engraving/rw/400/tread.cpp
  src/engraving/rw/compat/compatutils.cpp
  src/engraving/rw/compat/compatutils.h
  src/engraving/style/styledef.cpp
  src/engraving/tests/compat206_data/articulations-double-ref.mscx
  src/engraving/tests/compat206_data/articulations-ref.mscx
  src/engraving/tests/rhythmicGrouping_data/groupShortenNotes-ref.mscx
  src/importexport/guitarpro/internal/gtp/gpconverter.cpp
  src/importexport/guitarpro/internal/importgtp.cpp
  src/importexport/musicxml/internal/musicxml/exportxml.cpp
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/inspector/types/articulationtypes.h
  src/inspector/view/qml/MuseScore/Inspector/notation/articulations/ArticulationSettings.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/ornaments/OrnamentSettings.qml
Labels: vtests

#17717 Fix start repeat distance bug
  src/engraving/libmscore/segment.cpp
  vtest/scores/barline-3.mscz
Labels: vtests

#17768 ornament_intervals_playback
  src/engraving/libmscore/ornament.cpp
  src/engraving/libmscore/trill.cpp
  src/engraving/libmscore/trill.h
  src/engraving/playback/filters/filterbase.h
  src/engraving/playback/filters/spannerfilter.h
  src/engraving/playback/metaparsers/internal/spannersmetaparser.h
  src/engraving/playback/renderers/ornamentsrenderer.cpp
  src/engraving/playback/renderers/ornamentsrenderer.h
  src/engraving/types/types.h
  src/inspector/models/notation/ornaments/ornamentsettingsmodel.cpp
  src/notation/internal/notationaccessibility.h
Labels: vtests

#17773 Update UI for articulation anchor
  src/engraving/layout/v0/chordlayout.cpp
  src/engraving/layout/v0/tlayout.cpp
  src/engraving/libmscore/ornament.cpp
  src/engraving/libmscore/ornament.h
  src/engraving/rw/read400/tread.cpp
  src/inspector/view/qml/MuseScore/Inspector/notation/articulations/ArticulationSettings.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/ornaments/OrnamentSettings.qml
  vtest/scores/bravura-8.mscx
  vtest/scores/bravura-8.mscz
  vtest/scores/gonville-8.mscx
  vtest/scores/gonville-8.mscz
  vtest/scores/ornament-2.mscz
Labels: vtests
