Repository musescore/MuseScore, pull requests merged in 2023-12, with the labels that each got.

#20242 Introduce separate line width style for tab bends
  src/engraving/dom/guitarbend.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/notation/view/widgets/editstyle.cpp
  src/notation/view/widgets/editstyle.ui
Labels: vtests, engraving

#20372 [bug-19963] Fixed layout of spacer. 4.2.0
  src/engraving/rendering/dev/tlayout.cpp
Labels: vtests

#20357 Correct stem alignment for grace note bends on TAB
  src/engraving/dom/chord.cpp
  src/engraving/dom/chord.h
  src/engraving/rendering/dev/tlayout.cpp
  vtest/scores/guitarBend-9.mscz
Labels: vtests

#20278 Fixed Rect is null
  src/framework/draw/types/geometry.h
Labels: vtests

#20522 Two improvements to the logger
  src/engraving/dom/segment.cpp
  src/engraving/rw/xmlreader.cpp
  src/framework/global/thirdparty/kors_logger/src/logger.h
  src/framework/global/thirdparty/kors_logger/src/logstream.h
  src/importexport/guitarpro/internal/importgtp.cpp
Labels: dev

#20648 Fix bug on cross beamed rest
  src/engraving/rendering/dev/pagelayout.cpp
  vtest/scores/beams-26.mscz
Labels: vtests
