Repository musescore/MuseScore, pull requests merged in 2023-06, with the labels that each got.

#17783 Fix ornament accidental brackets
  src/engraving/libmscore/articulation.cpp
  src/engraving/libmscore/ornament.cpp
Labels: vtests

#17806 Ornament accidental improvements
  src/engraving/layout/v0/measurelayout.cpp
  src/engraving/libmscore/key.cpp
  src/engraving/libmscore/key.h
  src/engraving/libmscore/note.cpp
  src/engraving/libmscore/ornament.cpp
  src/engraving/libmscore/ornament.h
  src/engraving/types/types.h
  vtest/scores/ornament-6.mscz
Labels: vtests

#17797 Fix #17789: Fix a bug in the beam/tremolo beam count calculation
  src/engraving/layout/v0/beamlayout.cpp
  src/engraving/layout/v0/beamtremololayout.cpp
  src/engraving/libmscore/chord.cpp
  vtest/scores/tremolo-in-beam.mscz
Labels: vtests

#17582 Fix GH#16625: Rename margin to padding
  src/engraving/libmscore/property.cpp
  src/inspector/view/qml/MuseScore/Inspector/common/FrameSettings.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/frames/internal/HorizontalMarginsSection.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/frames/internal/VerticalMarginsSection.qml
  src/notation/view/widgets/editstyle.ui
Labels: strings

#17782 Fix translatable texts: "bar line(s)" to "barline(s)"
  src/engraving/libmscore/property.cpp
  src/inspector/view/qml/MuseScore/Inspector/notation/clefs/ClefSettings.qml
  src/inspector/view/qml/MuseScore/Inspector/notation/dynamics/DynamicsSettings.qml
  src/notation/view/widgets/editstyle.ui
Labels: strings

#17734 Fix: My account -> My accounts
  src/cloud/qml/MuseScore/Cloud/AccountInfoButton.qml
Labels: strings

#17974 Fix the "Replace existing online score" option
  src/cloud/musescorecom/musescorecomservice.cpp
Labels: P1, regression, cloud

#17969 Fix default visibility when publishing existing cloud score
  src/project/internal/saveprojectscenario.cpp
Labels: P1, regression, cloud

#17951 Rests improvement
  src/engraving/layout/v0/chordlayout.cpp
  src/engraving/libmscore/utils.cpp
  src/engraving/libmscore/utils.h
  vtest/scores/rests-5.mscz
Labels: vtests

#17840 Fix #16878: Enforce same lyric alignment stem flip
  src/engraving/layout/v0/lyricslayout.cpp
Labels: vtests

#18003 Correction on hairpin-dynamic-expression groups
  src/engraving/layout/v0/tlayout.cpp
  vtest/scores/dynamics-4.mscz
Labels: vtests

#18064 Reset rest vertical offsets for pre-410 scores
  src/engraving/rw/compat/compatutils.cpp
  src/engraving/rw/compat/compatutils.h
Labels: vtests

#18115 Fix tremolo bug in full TAB staves
  src/engraving/libmscore/chord.cpp
  vtest/scores/tremolo-tab.mscz
Labels: vtests

#18142 Don't use backticks delimiter syntax for translatable strings
  src/project/qml/MuseScore/Project/internal/ScoresPage/CloudScoresView.qml
Labels: strings

#18024 Implement #17999: Convert all combined articulations from pre-410 scores to their components
  src/braille/tests/data/testArticulations_Example_22.1_MBC2015.mscx
  src/engraving/rw/compat/compatutils.cpp
  src/engraving/rw/compat/compatutils.h
  src/engraving/tests/compat114_data/articulations-ref.mscx
  src/engraving/tests/compat206_data/articulations-double-ref.mscx
  src/engraving/tests/compat206_data/articulations-ref.mscx
  src/engraving/tests/timesig_data/timesig-03-ref.mscx
  src/engraving/tests/timesig_data/timesig-05-ref.mscx
  vtest/scores/articulation-3.mscz
  vtest/scores/articulation-4.mscz
  vtest/scores/articulation-6.mscz
  vtest/scores/staff-1.mscx
  vtest/scores/staff-1.mscz
Labels: vtests

#17983 Fix old project migration bugs
  src/engraving/rw/read206/read206.cpp
  src/project/internal/notationproject.cpp
Labels: vtests

#18169 fix #18143 gliss line direction for 8va and microtonal notes
  src/engraving/layout/v0/tlayout.cpp
  src/engraving/libmscore/accidental.cpp
  src/engraving/libmscore/accidental.h
  vtest/scores/gliss-4.mscz
Labels: vtests

#18216 Display info message when trying to delete a key signature that can't be deleted
  src/engraving/libmscore/edit.cpp
  src/engraving/libmscore/mscore.cpp
  src/engraving/libmscore/mscore.h
  src/notation/internal/notationinteraction.cpp
Labels: strings

#18259 Tremolo Fixes for #18173
  src/engraving/layout/v0/beamtremololayout.cpp
  src/engraving/layout/v0/beamtremololayout.h
  src/engraving/layout/v0/chordlayout.cpp
  src/engraving/libmscore/noteentry.cpp
  src/engraving/libmscore/tremolo.cpp
  vtest/scores/trem-beam-styles.mscz
  vtest/scores/trem-layout-order.mscz
  vtest/scores/trem-with-extreme-chords.mscz
Labels: vtests
