Repository musescore/MuseScore, pull requests merged in 2024-07, with the labels that each got.

#23532 Add elements written after the end of the score to the final tick
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/importexport/musicxml/tests/data/testSystemObjectStaves.xml
  src/importexport/musicxml/tests/data/testSystemObjectStaves_ref.mscx
Labels: crash, MusicXML

#23392 Improve laissez vib articulation placement
  src/engraving/dom/articulation.cpp
  src/engraving/dom/articulation.h
  src/engraving/dom/shadownote.cpp
  src/engraving/rendering/dev/chordlayout.cpp
  src/engraving/rendering/dev/chordlayout.h
  src/engraving/rendering/dev/slurtielayout.h
  src/engraving/rendering/dev/tlayout.cpp
  src/engraving/rendering/paddingtable.cpp
  vtest/scores/lv-ties.mscz
Labels: vtests

#23529 New cross staff beam positions
  src/engraving/dom/beam.h
  src/engraving/dom/beambase.h
  src/engraving/rendering/dev/beamlayout.cpp
  src/engraving/rendering/dev/beamtremololayout.cpp
  src/engraving/rendering/dev/beamtremololayout.h
  src/engraving/rendering/dev/tremololayout.cpp
  src/engraving/rendering/stable/beamlayout.cpp
  src/engraving/rendering/stable/beamtremololayout.cpp
  src/engraving/rendering/stable/beamtremololayout.h
  src/engraving/rendering/stable/tremololayout.cpp
  src/importexport/mei/tests/data/cross-staff-01.mscx
  vtest/scores/cross-10.mscz
  vtest/scores/tuplets-8.mscz
Labels: vtests

#23566 Ignore invisible accidentals for stacking
  src/engraving/rendering/dev/accidentalslayout.cpp
  src/engraving/rendering/dev/accidentalslayout.h
  src/inspector/models/notation/accidentals/accidentalsettingsmodel.cpp
  vtest/scores/accidental-37.mscz
Labels: vtests

#23575 Improved distances and centering of cross-staff beams
  src/engraving/dom/beam.cpp
  src/engraving/dom/beam.h
  src/engraving/dom/beambase.h
  src/engraving/rendering/dev/beamtremololayout.cpp
  src/engraving/rendering/dev/beamtremololayout.h
  src/engraving/rendering/dev/systemlayout.cpp
  src/engraving/rendering/dev/systemlayout.h
  src/importexport/mei/tests/data/cross-staff-01.mscx
Labels: vtests

#23624 Correct MMR margins after header segments
  share/templates/01-General/01-Treble_Clef/score_style.mss
  share/templates/01-General/02-Bass_Clef/score_style.mss
  share/templates/01-General/03-Grand_Staff/score_style.mss
  share/templates/02-Choral/01-SATB/score_style.mss
  share/templates/02-Choral/02-SATB_+_Organ/score_style.mss
  share/templates/02-Choral/03-SATB_+_Piano/score_style.mss
  share/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
  share/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
  share/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
  share/templates/02-Choral/07-Voice_+_Piano/score_style.mss
  share/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
  share/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
  share/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
  share/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
  share/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
  share/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
  share/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
  share/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
  share/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
  share/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
  share/templates/04-Solo/01-Guitar/score_style.mss
  share/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
  share/templates/04-Solo/03-Guitar_Tablature/score_style.mss
  share/templates/04-Solo/04-Piano/score_style.mss
  share/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
  share/templates/05-Jazz/02-Big_Band/score_style.mss
  share/templates/05-Jazz/03-Jazz_Combo/score_style.mss
  share/templates/06-Popular/01-Rock_Band/score_style.mss
  share/templates/06-Popular/02-Bluegrass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
  share/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
  share/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
  share/templates/08-Orchestral/03-String_Orchestra/score_style.mss
  src/engraving/rendering/dev/measurelayout.cpp
  src/engraving/style/styledef.cpp
  src/importexport/musicxml/tests/data/testSystemDividers.xml
Labels: vtests

#23657 Calculate spanner start and end elements before cloning to part
  src/engraving/dom/excerpt.cpp
Labels: MusicXML

#22860 Avoid collisions in full tab layout
  src/engraving/dom/note.cpp
  src/engraving/dom/note.h
  src/engraving/rendering/dev/chordlayout.cpp
  src/engraving/rendering/dev/tdraw.cpp
  src/engraving/rendering/dev/tlayout.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  vtest/scores/tablature-2.mscz
  vtest/scores/tablature-5.mscz
Labels: vtests

#23732 Set ledger line mag value equal to its parent chord
  src/engraving/rendering/dev/tlayout.cpp
Labels: engraving

#23639 Outside ties ignore accidentals
  src/engraving/rendering/dev/slurtielayout.cpp
  vtest/scores/tie-20.mscz
Labels: vtests

#23737 Fix alignment for dynamics or expressions that are not aligned to the baseline
  src/engraving/rendering/dev/alignmentlayout.cpp
Labels: engraving

#23114 Extend small note stems to 2nd outermost line
  src/engraving/dom/chord.cpp
  src/engraving/rendering/dev/beamtremololayout.cpp
  src/engraving/rendering/dev/beamtremololayout.h
  vtest/scores/small-beams-2.mscz
Labels: vtests

#23770 Fix cross-staff slur glitch
  src/engraving/rendering/dev/pagelayout.cpp
Labels: P1, engraving
