Repository musescore/MuseScore, pull requests merged in 2024-02, with the labels that each got.

#21370 Fix rest vertical pos with arpeggio
  src/engraving/rendering/dev/chordlayout.cpp
  vtest/scores/rests-8.mscz
Labels: vtests

#21395 Use correct track for melisma length on XML import
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
Labels: MusicXML

#20934 'Musical symbols scale' option
  src/engraving/dom/mscore.h
  src/engraving/dom/ottava.cpp
  src/engraving/dom/pedal.cpp
  src/engraving/dom/property.cpp
  src/engraving/dom/property.h
  src/engraving/dom/textbase.cpp
  src/engraving/rendering/dev/tupletlayout.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/style/textstyle.cpp
  src/engraving/style/textstyle.h
  src/engraving/tests/compat206_data/textstyles.mscx
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/importexport/musicxml/tests/data/testLayout.xml
  src/notation/view/widgets/editstyle.cpp
  src/notation/view/widgets/editstyle.h
  src/notation/view/widgets/editstyle.ui
Labels: vtests

#21433 MusicXML: export more color details
  src/importexport/musicxml/internal/musicxml/exportxml.cpp
  src/importexport/musicxml/tests/data/testColorExport.mscx
  src/importexport/musicxml/tests/data/testColorExport_ref.xml
Labels: MusicXML

#21192 Fix cross staff tie layout
  src/engraving/dom/tie.cpp
  src/engraving/dom/tie.h
  src/engraving/rendering/dev/measurelayout.cpp
  src/engraving/rendering/dev/slurtielayout.cpp
  vtest/scores/tie-18.mscz
Labels: vtests

#21371 TAB ghost and dead notes refinements
  src/engraving/dom/cmd.cpp
  src/engraving/dom/note.cpp
  src/engraving/dom/note.h
  src/engraving/dom/score.h
  src/engraving/dom/stafftype.cpp
  src/engraving/dom/stafftype.h
  src/engraving/rendering/dev/chordlayout.cpp
  src/engraving/rendering/dev/guitarbendlayout.cpp
  src/engraving/rendering/dev/tdraw.cpp
  src/engraving/rendering/dev/tlayout.cpp
  src/engraving/rendering/single/singledraw.cpp
  src/engraving/rw/read400/tread.cpp
  src/engraving/types/types.h
Labels: vtests

#21506 Style dialog tweaks
  src/notation/view/widgets/editstyle.cpp
  src/notation/view/widgets/editstyle.ui
Labels: strings

#21440 Ignore: minTieLength for invisible ties, invisible note dots
  src/engraving/rendering/dev/chordlayout.cpp
  src/engraving/rendering/dev/horizontalspacing.cpp
  src/engraving/rendering/dev/slurtielayout.cpp
  vtest/scores/tie-19.mscz
Labels: vtests

#21443 Correct accidentals for cross-staff notes
  src/engraving/dom/cmd.cpp
  src/engraving/dom/measure.cpp
  src/engraving/rendering/dev/modifydom.cpp
  vtest/scores/cross-9.mscz
  vtest/scores/narrow-spacing-2.mscz
Labels: vtests

#21126 French style beams option
  src/engraving/rendering/dev/beamlayout.cpp
  src/engraving/rendering/dev/beamlayout.h
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/framework/uicomponents/qml/MuseScore/UiComponents/StyledGroupBox.qml
  src/framework/uicomponents/qml/MuseScore/UiComponents/qmldir
  src/framework/uicomponents/uicomponents.qrc
  src/notation/notationscene.qrc
  src/notation/qml/MuseScore/NotationScene/internal/EditStyle/BeamsPage.qml
  src/notation/qml/MuseScore/NotationScene/internal/EditStyle/beam_style_french.svg
  src/notation/qml/MuseScore/NotationScene/internal/EditStyle/beam_style_regular.svg
  src/notation/view/styledialog/beamspagemodel.cpp
  src/notation/view/styledialog/beamspagemodel.h
  src/notation/view/widgets/editstyle.cpp
  vtest/scores/beams-french-style.mscz
Labels: vtests, engraving

#21518 Scale header and footer font size to fit within margins
  src/importexport/musicxml/internal/musicxml/importmxmlpass1.cpp
  src/importexport/musicxml/tests/data/testCopyrightScale.xml
  src/importexport/musicxml/tests/data/testCopyrightScale_ref.mscx
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: vtests

#21728 Fix bug on barlines not show
  src/engraving/rendering/dev/tlayout.cpp
  vtest/scores/barline-5.mscz
Labels: vtests

#21729 Fix mmRest clef collision
  src/engraving/rendering/dev/measurelayout.cpp
  src/engraving/rendering/dev/tlayout.cpp
  vtest/scores/mmrest-16.mscz
Labels: vtests

#21602 [MusicXML] export beams starting or ending on rests
  src/importexport/musicxml/internal/musicxml/exportxml.cpp
  src/importexport/musicxml/tests/data/testNotesRests2.xml
Labels: MusicXML

#21755 Dont add bracket to system with just HBox
  src/engraving/rendering/dev/systemlayout.cpp
  vtest/scores/brackets-2.mscz
Labels: vtests

#21762 Fret diagrams go before voltas in stacking order
  src/engraving/rendering/dev/systemlayout.cpp
  vtest/scores/stacking-order.mscz
Labels: vtests
