Repository musescore/MuseScore, pull requests merged in 2024-10, with the labels that each got.

#24818 Calculate up for user modified tremolos
  src/engraving/rendering/score/chordlayout.cpp
  src/engraving/rendering/score/chordlayout.h
  src/engraving/rendering/score/tremololayout.cpp
  src/engraving/rendering/score/tremololayout.h
  vtest/scores/tremolo-adjusted.mscz
Labels: vtests

#25153 [4.4.3] fixed scan old plugins
  src/framework/extensions/internal/legacy/extpluginsloader.cpp
Labels: plugins

#25099 Segment-based horizontal spacing
  src/engraving/dom/measure.cpp
  src/engraving/dom/measure.h
  src/engraving/dom/note.cpp
  src/engraving/dom/segment.cpp
  src/engraving/dom/segment.h
  src/engraving/dom/system.cpp
  src/engraving/dom/system.h
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/score/chordlayout.cpp
  src/engraving/rendering/score/chordlayout.h
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/horizontalspacing.h
  src/engraving/rendering/score/layoutcontext.h
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/measurelayout.h
  src/engraving/rendering/score/scorehorizontalviewlayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/systemlayout.h
  src/engraving/tests/beam_data/wideBeams.mscx
  src/engraving/tests/layoutelements_tests.cpp
  src/engraving/tests/selectionrangedelete_data/selectionrangedelete06_partialnestedtuplets-ref.mscx
  src/importexport/musicxml/tests/data/testBeamModes_ref.mscx
  src/importexport/musicxml/tests/data/testExcessHiddenStaves_ref.mscx
  src/importexport/musicxml/tests/data/testLayout.xml
  src/importexport/musicxml/tests/data/testSystemDistance_ref.xml
  vtest/scores/lyrics-24.mscz
  vtest/scores/lyrics-25.mscz
Labels: vtests

#25197 Cross-beam spacing correction
  src/engraving/rendering/score/horizontalspacing.cpp
  vtest/scores/cross-11.mscz
Labels: vtests, engraving

#25156 Incremental slur improvements and code cleanup
  src/engraving/rendering/score/slurtielayout.cpp
  src/engraving/rendering/score/slurtielayout.h
Labels: vtests
