Repository musescore/MuseScore, pull requests merged in 2024-08, with the labels that each got.

#23825 Sticking layout improvements
  share/templates/01-General/01-Treble_Clef/score_style.mss
  share/templates/01-General/02-Bass_Clef/score_style.mss
  share/templates/01-General/03-Grand_Staff/score_style.mss
  share/templates/02-Choral/01-SATB/score_style.mss
  share/templates/02-Choral/02-SATB_+_Organ/score_style.mss
  share/templates/02-Choral/03-SATB_+_Piano/score_style.mss
  share/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
  share/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
  share/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
  share/templates/02-Choral/07-Voice_+_Piano/score_style.mss
  share/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
  share/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
  share/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
  share/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
  share/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
  share/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
  share/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
  share/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
  share/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
  share/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
  share/templates/04-Solo/01-Guitar/score_style.mss
  share/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
  share/templates/04-Solo/03-Guitar_Tablature/score_style.mss
  share/templates/04-Solo/04-Piano/score_style.mss
  share/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
  share/templates/05-Jazz/02-Big_Band/score_style.mss
  share/templates/05-Jazz/03-Jazz_Combo/score_style.mss
  share/templates/06-Popular/01-Rock_Band/score_style.mss
  share/templates/06-Popular/02-Bluegrass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
  share/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
  share/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
  share/templates/08-Orchestral/03-String_Orchestra/score_style.mss
  src/engraving/dom/engravingitem.h
  src/engraving/rendering/dev/alignmentlayout.cpp
  src/engraving/rendering/dev/alignmentlayout.h
  src/engraving/rendering/dev/systemlayout.cpp
  src/engraving/rendering/dev/tlayout.cpp
  src/engraving/style/styledef.cpp
  vtest/scores/sticking-1.mscz
Labels: vtests

#23783 Ensure gap rest consistency - and several other fixes and improvements for situations with complext track mappings
  src/engraving/dom/check.cpp
  src/engraving/dom/edit.cpp
  src/engraving/dom/property.cpp
  src/engraving/dom/staff.cpp
  src/engraving/dom/staff.h
  src/engraving/tests/exchangevoices_data/undoChangeVoice02-ref.mscx
  src/engraving/tests/implode_explode_data/implodeScore.mscx
  src/engraving/tests/implode_explode_data/implodeScore01-ref.mscx
  src/engraving/tests/implode_explode_data/implodeScore02-ref.mscx
  src/engraving/tests/readwriteundoreset_data/slurs.mscx
  src/engraving/tests/split_data/split184061-other-inst-only-one-tie-ref.mscx
  src/importexport/mei/internal/meiexporter.cpp
Labels: vtests

#23868 Fix lyrics odd-even style bug
  src/engraving/dom/lyrics.cpp
  src/engraving/dom/lyrics.h
  src/engraving/rendering/dev/lyricslayout.cpp
  src/engraving/rendering/stable/lyricslayout.cpp
  src/engraving/rw/read114/read114.cpp
  src/engraving/rw/read400/tread.cpp
  src/engraving/rw/read410/tread.cpp
  src/notation/internal/notationinteraction.cpp
  vtest/scores/lyrics-21.mscz
Labels: vtests

#23907 Fix local time signature spacing bug
  src/engraving/rendering/dev/measurelayout.cpp
  vtest/scores/timesig-2.mscz
  vtest/scores/timesig-3.mscz
Labels: vtests

#23853 Layout system spanners when top stave is hidden
  src/engraving/rendering/dev/systemlayout.cpp
  vtest/scores/system-objects.mscz
Labels: vtests

#23947 Correct migration of dynamic position and voice assignment
  src/engraving/compat/engravingcompat.cpp
Labels: vtests, engraving, UX/interaction

#23946 Fix nested tuplet crash
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
Labels: crash, MusicXML

#23815 Allow adding chordlines to grace notes
  src/engraving/dom/edit.cpp
  src/engraving/rendering/dev/tdraw.cpp
  src/engraving/rendering/dev/tlayout.cpp
  vtest/scores/chordline-2.mscz
Labels: vtests

#23875 Convert LINE_WIDTH property to spatium
  src/engraving/dom/ambitus.cpp
  src/engraving/dom/bend.cpp
  src/engraving/dom/bend.h
  src/engraving/dom/box.cpp
  src/engraving/dom/box.h
  src/engraving/dom/engravingitem.h
  src/engraving/dom/line.cpp
  src/engraving/dom/line.h
  src/engraving/dom/lyricsline.cpp
  src/engraving/dom/ottava.cpp
  src/engraving/dom/pedal.cpp
  src/engraving/dom/property.cpp
  src/engraving/dom/property.h
  src/engraving/dom/stem.cpp
  src/engraving/dom/stem.h
  src/engraving/dom/stretchedbend.cpp
  src/engraving/dom/stretchedbend.h
  src/engraving/dom/system.cpp
  src/engraving/dom/tuplet.cpp
  src/engraving/dom/tuplet.h
  src/engraving/dom/volta.cpp
  src/engraving/rendering/dev/beamlayout.cpp
  src/engraving/rendering/dev/beamtremololayout.cpp
  src/engraving/rendering/dev/chordlayout.cpp
  src/engraving/rendering/dev/lyricslayout.cpp
  src/engraving/rendering/dev/scorehorizontalviewlayout.cpp
  src/engraving/rendering/dev/systemlayout.cpp
  src/engraving/rendering/dev/tdraw.cpp
  src/engraving/rendering/dev/tlayout.cpp
  src/engraving/rendering/single/singledraw.cpp
  src/engraving/rendering/single/singlelayout.cpp
  src/engraving/rendering/stable/beamlayout.cpp
  src/engraving/rendering/stable/beamtremololayout.cpp
  src/engraving/rendering/stable/chordlayout.cpp
  src/engraving/rendering/stable/lyricslayout.cpp
  src/engraving/rendering/stable/scorehorizontalviewlayout.cpp
  src/engraving/rendering/stable/systemlayout.cpp
  src/engraving/rendering/stable/tdraw.cpp
  src/engraving/rendering/stable/tlayout.cpp
  src/engraving/rw/read114/read114.cpp
  src/engraving/rw/read206/read206.cpp
  src/engraving/rw/read400/tread.cpp
  src/engraving/rw/read410/tread.cpp
  src/engraving/rw/write/twrite.cpp
  src/engraving/tests/compat114_data/pedal-ref.mscx
  src/inspector/models/notation/ambituses/ambitussettingsmodel.cpp
Labels: vtests

#24010 Items with custom x-offset (as opposed to y-offset) can still be centered
  src/engraving/rendering/dev/systemlayout.cpp
Labels: vtests, engraving

#23768 Implement cutout shapes for clefs and dynamics in preparation of new Leland release
  src/engraving/dom/clef.cpp
  src/engraving/dom/clef.h
  src/engraving/dom/textbase.cpp
  src/engraving/rendering/dev/horizontalspacing.cpp
  src/engraving/rendering/dev/tlayout.cpp
Labels: vtests

#24004 Correct style definition for harp pedal text diagram
  src/engraving/style/styledef.cpp
Labels: regression nightly

#24011 Reimplement ledger lines
  src/engraving/dom/chord.cpp
  src/engraving/dom/chord.h
  src/engraving/dom/ledgerline.cpp
  src/engraving/dom/ledgerline.h
  src/engraving/dom/scoretree.cpp
  src/engraving/rendering/dev/accidentalslayout.cpp
  src/engraving/rendering/dev/chordlayout.cpp
  src/engraving/rendering/dev/slurtielayout.cpp
  src/engraving/rendering/stable/chordlayout.cpp
  src/engraving/rendering/stable/slurtielayout.cpp
Labels: vtests, P1, crash

#24041 Support more symbol fonts used in xml files
  src/framework/global/types/string.cpp
  src/framework/global/types/string.h
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.h
  src/importexport/musicxml/internal/musicxml/musicxmlsupport.h
Labels: MusicXML

#24070 Fixed Do solfège noteheads - rollback
  src/engraving/dom/note.cpp
Labels: regression nightly

#24046 Tuplet avoid staves now ONLY avoids staves
  src/engraving/dom/cmd.cpp
  src/engraving/rendering/score/autoplace.cpp
  src/engraving/rendering/score/tupletlayout.cpp
  src/engraving/style/style.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/tests/tuplet_data/nestedTuplets_addStaff-ref.mscx
  src/notation/view/widgets/editstyle.cpp
  vtest/scores/tuplets-9.mscz
Labels: vtests

#24065 Infer sticking from lyrics
  src/importexport/musicxml/internal/musicxml/importmxmlpass1.h
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.h
  src/importexport/musicxml/internal/musicxml/importxmlfirstpass.cpp
  src/importexport/musicxml/tests/data/testLyricBracket_ref.mscx
  src/importexport/musicxml/tests/data/testSticking.xml
  src/importexport/musicxml/tests/data/testStickingLyrics.xml
  src/importexport/musicxml/tests/data/testStickingLyrics_ref.mscx
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: vtests, MusicXML

#24155 Correct staccato placement on stem side of french-style beams
  src/engraving/dom/stem.h
  src/engraving/rendering/score/beamlayout.cpp
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/beams-french-style-2.mscz
Labels: vtests, engraving

#24239 Add Campania back
  src/engraving/engravingmodule.cpp
Labels: vtests

#24069 Don't add credit frames past page 1 on XML import
  src/importexport/musicxml/internal/musicxml/importmxmlpass1.cpp
  src/importexport/musicxml/internal/musicxml/importmxmlpass1.h
  src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
  src/importexport/musicxml/tests/data/testBarlineLoc_ref.mscx
  src/importexport/musicxml/tests/data/testBeamModes_ref.mscx
  src/importexport/musicxml/tests/data/testBracketTypes_ref.mscx
  src/importexport/musicxml/tests/data/testCopyrightScale_ref.mscx
  src/importexport/musicxml/tests/data/testCueGraceNotes_ref.mscx
  src/importexport/musicxml/tests/data/testCueNotes3_ref.mscx
  src/importexport/musicxml/tests/data/testDSalCodaMisplaced_ref.mscx
  src/importexport/musicxml/tests/data/testDSalCoda_ref.mscx
  src/importexport/musicxml/tests/data/testExcessHiddenStaves_ref.mscx
  src/importexport/musicxml/tests/data/testImportDrums_ref.mscx
  src/importexport/musicxml/tests/data/testInferredCredits1_ref.mscx
  src/importexport/musicxml/tests/data/testInferredFingerings_ref.mscx
  src/importexport/musicxml/tests/data/testLyricBracket_ref.mscx
  src/importexport/musicxml/tests/data/testMeasureStyleSlash_ref.mscx
  src/importexport/musicxml/tests/data/testNegativeOffset_ref.mscx
  src/importexport/musicxml/tests/data/testPartNames_ref.mscx
  src/importexport/musicxml/tests/data/testPedalChangesBroken_ref.mscx
  src/importexport/musicxml/tests/data/testPlacementDefaults_ref.mscx
  src/importexport/musicxml/tests/data/testSecondVoiceMelismata_ref.mscx
  src/importexport/musicxml/tests/data/testStaffEmptiness_ref.mscx
  src/importexport/musicxml/tests/data/testSystemObjectStaves_ref.mscx
  src/importexport/musicxml/tests/data/testTempoLineFermata_ref.mscx
  src/importexport/musicxml/tests/data/testTempoTextSpace1_ref.mscx
  src/importexport/musicxml/tests/data/testTempoTextSpace2_ref.mscx
  src/importexport/musicxml/tests/data/testTextOrder_ref.mscx
  src/importexport/musicxml/tests/data/testTextQuirkInference_ref.mscx
  src/importexport/musicxml/tests/data/testTitleSwapMu_ref.mscx
  src/importexport/musicxml/tests/data/testTitleSwapSib_ref.mscx
  src/importexport/musicxml/tests/data/testUnterminatedTies_ref.mscx
  src/importexport/musicxml/tests/data/testVoltaHiding_ref.mscx
  src/importexport/musicxml/tests/data/testWedgeOffset_ref.mscx
Labels: MusicXML

#24215 Fix dynamic staff centering for some instruments
  src/engraving/dom/instrument.cpp
Labels: vtests

#24279 Fix dynamic voicing edge case
  src/engraving/dom/engravingitem.cpp
Labels: P2, engraving
