Repository musescore/MuseScore, pull requests merged in 2024-09, with the labels that each got.

#24381 Fix clefs issue with hairpins and anchors visualization
  src/engraving/dom/hairpin.cpp
  src/engraving/rendering/score/measurelayout.cpp
  vtest/scores/clefSpacing-2.mscz
Labels: vtests

#24283 Stave offset fixes
  src/engraving/dom/engravingitem.h
  src/engraving/dom/keysig.cpp
  src/engraving/dom/keysig.h
  src/engraving/dom/timesig.cpp
  src/engraving/dom/timesig.h
  src/engraving/rendering/score/alignmentlayout.cpp
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/staff-offset-2.mscz
Labels: vtests

#24375 Correct beam height in groups of 3
  src/engraving/rendering/score/beamtremololayout.cpp
  src/importexport/mei/tests/data/tuplet-02.mscx
  vtest/scores/beams-28.mscz
Labels: vtests

#24373 Decrease flag to notehead padding
  src/engraving/rendering/paddingtable.cpp
  src/importexport/musicxml/tests/data/testLayout.xml
Labels: engraving

#24432 Fix missing volta on last measure of system
  src/engraving/dom/volta.cpp
Labels: vtests

#24384 Fix layout issues and change combine voice property to auto/on/off
  src/engraving/dom/chord.cpp
  src/engraving/dom/chord.h
  src/engraving/dom/property.cpp
  src/engraving/rendering/score/chordlayout.cpp
  src/engraving/rw/read410/tread.cpp
  src/inspector/types/commontypes.h
  src/inspector/view/qml/MuseScore/Inspector/notation/notes/HeadSettings.qml
  vtest/scores/separate-voice-layout-2.mscz
Labels: regression MS4, engraving

#24684 vst_audio_glitch_fix_442
  src/framework/vst/internal/synth/vstsynthesiser.cpp
  src/framework/vst/internal/vstaudioclient.cpp
  src/framework/vst/internal/vstaudioclient.h
Labels: regression nightly

#24695 Snap gradual tempo changes to MMR tempo text
  src/engraving/dom/gradualtempochange.cpp
  vtest/scores/mmrest-20.mscz
Labels: vtests

#24755 Return to old lyrics dash distrubution
  src/engraving/rendering/score/lyricslayout.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
Labels: vtests

#24749 Fix skyline conflicts on staff centering
  src/engraving/infrastructure/shape.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/systemlayout.h
Labels: vtests

#24689 Lyrics placement fixes
  src/engraving/rendering/score/lyricslayout.cpp
  vtest/scores/lyrics-22.mscz
  vtest/scores/lyrics-23.mscz
Labels: vtests

#24783 Set up cross measure durations earlier
  src/engraving/rendering/score/beamlayout.cpp
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/modifydom.cpp
  src/engraving/rendering/score/modifydom.h
  vtest/scores/cross-measure-1.mscz
Labels: vtests

#24804 Get correct measure for spanner middle & end segments
  src/engraving/dom/engravingitem.cpp
  vtest/scores/system-spanner.mscz
Labels: vtests

#24773 Limit barline span
  src/engraving/dom/barline.cpp
  vtest/scores/barline-6.mscz
Labels: vtests

#24569 Playback fixes for hairpins in combination with compound dynamics
  src/engraving/dom/hairpin.cpp
  src/engraving/playback/playbackcontext.cpp
  src/engraving/playback/playbackcontext.h
  src/engraving/playback/utils/expressionutils.h
  src/engraving/tests/playback/playbackcontext_data/dynamics/dynamics_compound.mscx
  src/engraving/tests/playback/playbackcontext_data/dynamics/dynamics_niente.mscx
  src/engraving/tests/playback/playbackcontext_tests.cpp
  src/engraving/tests/playback/playbackmodel_tests.cpp
Labels: regression MS4

#24816 Fix freeze on add title text
  src/engraving/dom/undo.cpp
Labels: vtests

#24936 Ignore invisible elements when laying out slurs
  src/engraving/rendering/score/slurtielayout.cpp
  vtest/scores/slurs-28.mscz
Labels: vtests

#24817 fix #24809 in section breaks, take also frames into account
  src/engraving/dom/measure.cpp
  vtest/scores/measure-number-02.mscz
Labels: vtests

#24920 Calculate beam position with BeamLayout methods
  src/engraving/rendering/score/chordlayout.cpp
  vtest/scores/beams-29.mscz
Labels: vtests
