Repository musescore/MuseScore, pull requests merged in 2025-01, with the labels that each got.

#25955 Fix binding loop in AudioResourceControl, and simplify
  src/playback/qml/MuseScore/Playback/internal/AudioResourceControl.qml
Labels: tech debt

#26012 Remove some redundant code from `cmdAddTimeSig`
  src/engraving/dom/edit.cpp
Labels: tech debt

#24125 GSoC '24 - Dynamics Popup - Part 1
  src/notation/CMakeLists.txt
  src/notation/internal/notationinteraction.cpp
  src/notation/notationmodule.cpp
  src/notation/notationscene.qrc
  src/notation/qml/MuseScore/NotationScene/internal/DynamicPopup.qml
  src/notation/qml/MuseScore/NotationScene/internal/ElementPopupLoader.qml
  src/notation/view/abstractelementpopupmodel.cpp
  src/notation/view/abstractelementpopupmodel.h
  src/notation/view/internal/dynamicpopupmodel.cpp
  src/notation/view/internal/dynamicpopupmodel.h
Labels: GSoC

#26038 [MusicXML] Export harp pedal texts
  src/engraving/dom/harppedaldiagram.h
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/tests/data/testHarpPedals.mscx
  src/importexport/musicxml/tests/data/testHarpPedals_ref.xml
Labels: MusicXML

#25883 Implement partial slurs
  src/engraving/dom/chordrest.cpp
  src/engraving/dom/chordrest.h
  src/engraving/dom/edit.cpp
  src/engraving/dom/engravingitem.cpp
  src/engraving/dom/engravingitem.h
  src/engraving/dom/measure.cpp
  src/engraving/dom/measure.h
  src/engraving/dom/measurebase.cpp
  src/engraving/dom/measurebase.h
  src/engraving/dom/note.cpp
  src/engraving/dom/note.h
  src/engraving/dom/score.h
  src/engraving/dom/slur.cpp
  src/engraving/dom/slur.h
  src/engraving/dom/system.cpp
  src/engraving/dom/tie.cpp
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/slurtielayout.cpp
  src/engraving/rendering/score/slurtielayout.h
  src/engraving/rw/read410/tread.cpp
  src/engraving/rw/write/twrite.cpp
  src/engraving/style/style.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/engraving/types/types.h
  src/engraving/types/typesconv.cpp
  src/notation/internal/notationinteraction.cpp
  src/notation/internal/notationinteraction.h
  vtest/scores/slurs-29.mscz
Labels: vtests

#23048 Add: Accessibility Panel - Score Style Preset option
  share/styles/CMakeLists.txt
  share/styles/MSN/16mm_MSN.mss
  share/styles/MSN/18mm_MSN.mss
  share/styles/MSN/20mm_MSN.mss
  share/styles/MSN/22mm_MSN.mss
  share/styles/MSN/25mm_MSN.mss
  share/styles/MSN/CMakeLists.txt
  src/engraving/style/style.cpp
  src/engraving/style/style.h
  src/engraving/types/types.h
  src/engraving/types/typesconv.cpp
  src/engraving/types/typesconv.h
  src/inspector/CMakeLists.txt
  src/inspector/models/abstractinspectormodel.h
  src/inspector/models/inspectorlistmodel.cpp
  src/inspector/models/score/scoreaccessibilitysettingsmodel.cpp
  src/inspector/models/score/scoreaccessibilitysettingsmodel.h
  src/inspector/view/inspector_resources.qrc
  src/inspector/view/qml/MuseScore/Inspector/InspectorSectionDelegate.qml
  src/inspector/view/qml/MuseScore/Inspector/score/ScoreAccessibilityInspectorView.qml
Labels: GSoC

#26048 Partial ties refinements
  src/engraving/dom/dom.cmake
  src/engraving/dom/edit.cpp
  src/engraving/dom/note.cpp
  src/engraving/dom/note.h
  src/engraving/dom/tie.cpp
  src/engraving/dom/tie.h
  src/engraving/dom/tiejumppointlist.cpp
  src/engraving/dom/tiejumppointlist.h
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/style/styledef.cpp
  src/framework/uicomponents/qml/Muse/UiComponents/ContextMenuLoader.qml
  src/framework/uicomponents/qml/Muse/UiComponents/StyledMenuLoader.qml
  src/framework/uicomponents/qml/Muse/UiComponents/internal/StyledMenu.qml
  src/notation/notationscene.qrc
  src/notation/qml/MuseScore/NotationScene/internal/CapoPopup.qml
  src/notation/qml/MuseScore/NotationScene/internal/HarpPedalPopup.qml
  src/notation/qml/MuseScore/NotationScene/internal/PartialTieMenuRowItem.qml
  src/notation/qml/MuseScore/NotationScene/internal/PartialTiePopup.qml
  src/notation/qml/MuseScore/NotationScene/internal/StringTuningsPopup.qml
  src/playback/qml/MuseScore/Playback/SoundFlagPopup.qml
Labels: vtests

#26132 Fix dynamic centering
  src/engraving/rendering/score/autoplace.h
  src/engraving/rendering/score/systemlayout.cpp
  vtest/scores/dynamics-12.mscz
Labels: vtests

#26187 Fix single line staff spacing
  src/engraving/rendering/score/pagelayout.cpp
  vtest/scores/staff-2.mscz
Labels: vtests

#26191 Fix layout of single-line and single-measure multirests
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/mmrest-23.mscz
Labels: vtests
