Repository musescore/MuseScore, pull requests merged in 2025-04, with the labels that each got.

#27389 Fix accidental ordering offsets
  src/engraving/rendering/score/accidentalslayout.cpp
  vtest/scores/accidental-40.mscz
Labels: vtests

#27276 Fix chord symbol spacing
  src/engraving/compat/engravingcompat.cpp
  src/engraving/compat/engravingcompat.h
  src/engraving/dom/harmony.cpp
  src/engraving/dom/harmony.h
  src/engraving/dom/ottava.cpp
  src/engraving/dom/segment.cpp
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/score/autoplace.cpp
  src/engraving/rendering/score/harmonylayout.cpp
  src/engraving/rendering/score/harmonylayout.h
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/tlayout.cpp
  src/notation/internal/notationinteraction.cpp
  vtest/scores/harmony-18.mscz
Labels: vtests

#27387 [MusicXML] Add support for accidental size
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlnotepitch.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/tests/data/testLayout.xml
Labels: MusicXML

#27040 [MusicXML] import swing
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h
  src/importexport/musicxml/tests/data/testSwing.xml
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: MusicXML

#27384 [MusicXML] Support fret diagram color
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
Labels: MusicXML

#27567 Fix porting error
  src/engraving/rendering/score/tlayout.cpp
Labels: vtests

#27586 Fix measure repeat extender
  src/engraving/dom/measurerepeat.h
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/tdraw.cpp
  src/engraving/rendering/score/tlayout.cpp
  src/engraving/rendering/score/tlayout.h
  vtest/scores/measure-repeat-6.mscz
Labels: vtests

#27585 MuseSampler: call setPosition before setPlaying
  src/framework/musesampler/internal/musesamplerwrapper.cpp
  src/framework/musesampler/internal/musesamplerwrapper.h
Labels: playback, MuseSounds

#27623 Port stuff
  src/engraving/dom/segment.cpp
  src/engraving/dom/textbase.cpp
  src/engraving/dom/textbase.h
  src/engraving/rendering/score/tdraw.cpp
  src/notation/internal/notationinteraction.cpp
  vtest/scores/tablature-6-fret-conflicts.mscz
Labels: vtests

#27652 Engraving 4.5.2 ports
  src/engraving/dom/note.cpp
  src/engraving/dom/tie.cpp
  src/engraving/rendering/score/slurtielayout.cpp
  src/engraving/tests/partialtie_data/toggle_delete.mscx
  src/engraving/tests/partialtie_tests.cpp
  vtest/scores/bigTimeSig-10.mscz
Labels: vtests

#27466 Prevent stale partial ties from being removed from the score twice
  src/engraving/dom/edit.cpp
  src/engraving/dom/score.h
  src/engraving/dom/slur.cpp
  src/engraving/dom/slur.h
  src/engraving/engravingproject.cpp
  src/engraving/tests/partialtie_data/delete_measure_test1.mscx
  src/engraving/tests/partialtie_data/delete_measure_test2.mscx
  src/engraving/tests/partialtie_tests.cpp
Labels: vtests

#27632 Performance improvement by reducing number of calls to beam layout
  src/engraving/dom/segment.cpp
  src/engraving/dom/segment.h
  src/engraving/rendering/score/beamlayout.cpp
  src/engraving/rendering/score/beamlayout.h
  src/engraving/rendering/score/chordlayout.cpp
  src/engraving/rendering/score/chordlayout.h
  src/engraving/rendering/score/pagelayout.cpp
  src/engraving/rendering/score/scorehorizontalviewlayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
Labels: vtests

#27778 Ensure percussion note popup only appears when shift is pressed
  src/notation/view/notationviewinputcontroller.cpp
Labels: percussion

#27817 Fix lyrics spacing on invisible rests
  src/engraving/dom/segment.cpp
  vtest/scores/lyrics-28.mscz
Labels: engraving

#25259 Account for durationType when merging rests
  src/engraving/dom/rest.cpp
Labels: engraving

#27886 New option for min header distance
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/notation/view/widgets/editstyle.cpp
  src/notation/view/widgets/editstyle.ui
Labels: engraving
