Repository musescore/MuseScore, pull requests merged in 2025-02, with the labels that each got.

#26286 Fix staff offset for clefs after barlines
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/staff-offset-3.mscz
Labels: vtests

#26220 L.V. tie playback
  src/engraving/playback/metaparsers/notearticulationsparser.cpp
  src/engraving/playback/metaparsers/notearticulationsparser.h
  src/engraving/playback/renderers/tremolorenderer.h
  src/engraving/playback/utils/arrangementutils.h
  src/framework/audio/internal/synthesizers/fluidsynth/fluidsequencer.cpp
  src/framework/audio/internal/synthesizers/fluidsynth/fluidsequencer.h
  src/framework/audio/internal/synthesizers/fluidsynth/fluidsynth.cpp
  src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h
  src/framework/midi/miditypes.h
  src/framework/mpe/mpetypes.h
  src/framework/mpe/resources/general_keyboard_articulations_profile.json
  src/framework/mpe/resources/general_strings_articulations_profile.json
  src/framework/musesampler/internal/apitypes.h
  src/framework/musesampler/internal/musesamplersequencer.cpp
  src/framework/vst/internal/synth/vstsequencer.cpp
  src/framework/vst/internal/synth/vstsequencer.h
  src/framework/vst/internal/synth/vstsynthesiser.cpp
  src/framework/vst/vsttypes.h
Labels: playback

#26310 Don't create sub beams based only on rest duration
  src/engraving/rendering/score/beamlayout.cpp
  vtest/scores/beams-30.mscz
Labels: vtests

#26350 Layout trill lines before dynamics
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/systemlayout.h
  vtest/scores/stacking-order-2.mscz
Labels: vtests

#24147 GSoC '24 - Dynamics Popup - Part 2
  src/engraving/dom/cmd.cpp
  src/engraving/dom/dynamic.cpp
  src/engraving/dom/dynamic.h
  src/engraving/dom/edit.cpp
  src/engraving/dom/editdata.h
  src/engraving/dom/score.h
  src/notation/inotationinteraction.h
  src/notation/internal/notationinteraction.cpp
  src/notation/internal/notationinteraction.h
  src/notation/tests/mocks/notationinteractionmock.h
Labels: GSoC

#26010 Fix crash on selecting arpeggio
  src/engraving/dom/arpeggio.cpp
  src/engraving/dom/tremolosinglechord.cpp
  src/engraving/dom/tremolosinglechord.h
  src/notation/view/notationviewinputcontroller.cpp
Labels: crash

#26213 Partials input refinements
  src/engraving/compat/midi/compatmidirender.cpp
  src/engraving/dom/chordrest.cpp
  src/engraving/dom/cmd.cpp
  src/engraving/dom/edit.cpp
  src/engraving/dom/lyrics.cpp
  src/engraving/dom/marker.h
  src/engraving/dom/navigate.cpp
  src/engraving/dom/navigate.h
  src/engraving/dom/slur.cpp
  src/engraving/dom/stafftype.cpp
  src/engraving/dom/tie.cpp
  src/engraving/dom/utils.cpp
  src/engraving/dom/utils.h
  src/engraving/dom/volta.h
  src/engraving/rendering/score/lyricslayout.cpp
  src/engraving/rendering/score/slurtielayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/notation/internal/notationinteraction.cpp
  vtest/scores/slurs-30.mscz
Labels: vtests, engraving, Pre-release feature issue

#26365 Fix wrong interaction between hairpins and dynamics when centering
  src/engraving/rendering/score/autoplace.cpp
  src/engraving/rendering/score/systemlayout.cpp
  vtest/scores/hairpins-3.mscz
Labels: vtests

#26380 Cross beam spacing improvements
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/horizontalspacing.h
  vtest/scores/cross-12.mscz
Labels: vtests

#26355 Masking refinements
  src/engraving/dom/textbase.cpp
  src/engraving/rendering/score/masklayout.cpp
  src/engraving/rendering/score/masklayout.h
  src/importexport/imagesexport/iimagesexportconfiguration.h
  src/importexport/imagesexport/internal/imagesexportconfiguration.cpp
  src/importexport/imagesexport/internal/imagesexportconfiguration.h
  src/importexport/imagesexport/internal/svggenerator.cpp
  src/importexport/imagesexport/internal/svggenerator.h
  src/importexport/imagesexport/internal/svgwriter.cpp
  src/project/qml/MuseScore/Project/internal/Export/SvgSettingsPage.qml
  src/project/view/exportdialogmodel.cpp
  src/project/view/exportdialogmodel.h
  vtest/scores/masking-1.mscz
Labels: vtests

#26434 Courtesy refinements
  src/engraving/dom/clef.cpp
  src/engraving/dom/segment.h
  src/engraving/dom/types.h
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/bigTimeSig-7.mscz
  vtest/scores/bigTimeSig-8.mscz
Labels: vtests

#26472 [MusicXML] export staff line details
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/tests/data/testDisplayStepOctave.mscx
  src/importexport/musicxml/tests/data/testInvisibleNote.mscx
  src/importexport/musicxml/tests/data/testLineDetails.mscx
  src/importexport/musicxml/tests/data/testLineDetails_ref.xml
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: MusicXML

#24152 GSoC '24 - Dynamics Popup - Part 3
  src/app/configs/data/shortcuts.xml
  src/app/configs/data/shortcuts_azerty.xml
  src/app/configs/data/shortcuts_mac.xml
  src/appshell/view/appmenumodel.cpp
  src/engraving/dom/edit.cpp
  src/engraving/dom/hairpin.cpp
  src/engraving/dom/hairpin.h
  src/engraving/dom/score.h
  src/notation/inotationinteraction.h
  src/notation/internal/notationactioncontroller.cpp
  src/notation/internal/notationinteraction.cpp
  src/notation/internal/notationinteraction.h
  src/notation/internal/notationuiactions.cpp
  src/notation/tests/mocks/notationinteractionmock.h
  src/notation/view/internal/dynamicpopupmodel.cpp
  src/notation/view/notationviewinputcontroller.cpp
  src/notation/view/noteinputbarmodel.cpp
Labels: GSoC

#26502 Update Leland
  fonts/leland/FONTLOG.txt
  fonts/leland/LICENSE.txt
  fonts/leland/Leland.otf
  fonts/leland/LelandText.otf
  fonts/leland/OFL-FAQ.txt
  fonts/leland/README.md
  fonts/leland/leland_metadata.json
Labels: vtests, engraving

#26566 Add slur to correct stave
  src/notation/internal/notationinteraction.cpp
Labels: engraving, Pre-release feature issue

#26473 Prevent crash on system with no measures
  src/engraving/rendering/score/pagelayout.cpp
Labels: crash

#26457 Alignment corrections with accidentals of different sizes
  src/engraving/rendering/score/accidentalslayout.cpp
  vtest/scores/accidental-38.mscz
  vtest/scores/accidental-39.mscz
Labels: vtests

#26555 System object correction
  src/engraving/dom/engravingitem.cpp
  src/engraving/dom/utils.cpp
  src/instrumentsscene/view/systemobjectslayertreeitem.cpp
Labels: P1, engraving, Pre-release feature issue

#26572 More system object refinements
  src/engraving/dom/engravingitem.cpp
  src/engraving/dom/timesig.cpp
  src/instrumentsscene/qml/MuseScore/InstrumentsScene/LayoutPanel.qml
  src/instrumentsscene/qml/MuseScore/InstrumentsScene/internal/LayoutControlPanel.qml
  src/instrumentsscene/qml/MuseScore/InstrumentsScene/internal/LayoutPanelAddButton.qml
  src/instrumentsscene/view/layoutpaneltreemodel.cpp
  src/instrumentsscene/view/layoutpaneltreemodel.h
  src/instrumentsscene/view/systemobjectslayertreeitem.cpp
  src/notation/inotation.h
  src/notation/internal/notation.cpp
  src/notation/internal/notation.h
Labels: engraving, UX/interaction, Pre-release feature issue

#26596 Partial lines after repeats fix
  src/notation/internal/notationinteraction.cpp
Labels: engraving, UX/interaction, Pre-release feature issue

#26711 Parentheses fixes
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/score/measurelayout.cpp
  vtest/scores/courtesyKeysigParens.mscz
Labels: vtests, engraving, Pre-release feature issue

#26642 Fix hang on entering tie
  src/engraving/rendering/score/slurtielayout.cpp
Labels: P1, crash, Pre-release feature issue

#26737 Attempt to fix mysterious crash in onSelectionChanged()
  src/playback/internal/playbackcontroller.cpp
Labels: crash

#26646 Fix text position for rehearsal marks and harmony
  src/engraving/rendering/score/autoplace.cpp
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/timeTickChordSymbols.mscz
Labels: vtests

#26753 Only create continuations when there is a courtesy on the same staff
  src/engraving/rendering/score/measurelayout.cpp
  vtest/scores/courtesy-changes-8.mscz
Labels: vtests, engraving, Pre-release feature issue

#26721 DrumInstrument constructor: take name as String instead of const char*
  src/engraving/dom/drumset.h
  src/engraving/types/typesconv.cpp
  src/engraving/types/typesconv.h
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
Labels: tech debt

#26772 Align text from textlines in skyline
  src/engraving/rendering/score/systemlayout.cpp
  vtest/scores/hairpins-4.mscz
Labels: vtests

#26764 Fix big courtesy time sig spacing
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/systemlayout.cpp
  vtest/scores/bigTimeSig-9.mscz
Labels: vtests

#26754 Added missing sound mappings for Taiko
  src/engraving/playback/mapping/percussionssetupdataresolver.cpp
  src/framework/audio/internal/synthesizers/fluidsynth/soundmapping.h
Labels: playback, percussion

#26806 Correct measure width when following begins with clef, key or time sig
  src/engraving/rendering/score/horizontalspacing.cpp
  vtest/scores/leadingNonChordSeg.mscz
Labels: vtests

#26826 Don't add duplicate segments to the end of measure
  src/engraving/rendering/score/modifydom.cpp
Labels: P2, engraving, UX/interaction, Pre-release feature issue
