Repository musescore/MuseScore, pull requests merged in 2025-09, with the labels that each got.

#29577 [MusicXML] import dynamics color and enclosing
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h
  src/importexport/musicxml/tests/data/testDynamics2.xml
Labels: MusicXML

#29680 Fix extra space in bass note slash
  src/engraving/dom/chordlist.cpp
  src/engraving/rendering/score/harmonylayout.cpp
  src/engraving/rw/read460/tread.cpp
Labels: vtests

#29751 Improved spacing of lyrics lines against right margin
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/horizontalspacing.h
  vtest/scores/lyrics-30.mscz
Labels: vtests

#29761 [4.6.0] Fix parsing of multiple verses
  src/engraving/playback/playbackcontext.cpp
  src/engraving/tests/playback/playbackcontext_data/lyrics_multiverses.mscx
  src/engraving/tests/playback/playbackcontext_tests.cpp
Labels: playback

#29749 Ignore laissez vib ties when laying out parentheses
  src/engraving/dom/slurtie.h
  src/engraving/rendering/score/parenthesislayout.cpp
  src/engraving/rendering/score/parenthesislayout.h
  src/engraving/rendering/score/slurtielayout.cpp
  vtest/scores/lv-3.mscz
  vtest/scores/lv-4.mscz
Labels: vtests

#29800 Jazz font tweaks
  src/engraving/data/chords/chords_jazz.xml
Labels: vtests

#29831 [4.6.0] Add --page option: export only specified page
  src/app/cmdoptions.h
  src/app/internal/commandlineparser.cpp
  src/app/internal/consoleapp.cpp
  src/converter/api/converterapi.cpp
  src/converter/iconvertercontroller.h
  src/converter/internal/compat/backendapi.cpp
  src/converter/internal/compat/backendapi.h
  src/converter/internal/convertercontroller.cpp
  src/converter/internal/convertercontroller.h
  src/engraving/compat/writescorehook.cpp
  src/engraving/compat/writescorehook.h
  src/engraving/dom/masterscore.cpp
  src/engraving/dom/score.cpp
  src/engraving/engravingproject.cpp
  src/engraving/engravingproject.h
  src/engraving/rw/iwriter.h
  src/engraving/rw/mscsaver.cpp
  src/engraving/rw/mscsaver.h
  src/engraving/rw/write/staffwrite.cpp
  src/engraving/rw/write/staffwrite.h
  src/engraving/rw/write/writecontext.h
  src/engraving/rw/write/writer.cpp
  src/engraving/rw/write/writer.h
  src/engraving/tests/utils/scorerw.cpp
  src/framework/audio/worker/audioworkermodule.cpp
  src/importexport/bb/tests/testbase.cpp
  src/importexport/bww/tests/testbase.cpp
  src/importexport/imagesexport/internal/pdfwriter.cpp
  src/notation/inotationelements.h
  src/notation/internal/mscnotationwriter.cpp
  src/notation/internal/notationelements.cpp
  src/notation/internal/notationelements.h
  src/notation/notationtypes.h
  src/notation/view/notationnavigator.cpp
  src/notation/view/notationnavigator.h
  src/project/inotationproject.h
  src/project/internal/notationproject.cpp
  src/project/internal/notationproject.h
  src/project/types/projecttypes.h
Labels: cli

#29915 Increase tempo line padding
  src/engraving/rendering/score/tlayout.cpp
Labels: vtests, engraving

#29935 Change stacking order for system text
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/systemlayout.h
  vtest/scores/stacking-order.mscz
Labels: vtests

#29940 Fix tie vs accidental
  src/engraving/rendering/score/guitarbendlayout.cpp
  src/engraving/rendering/score/slurtielayout.cpp
  vtest/scores/tie-27.mscz
Labels: vtests

#27422 [MusicXML] invisible notations
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h
  src/importexport/musicxml/tests/data/testExcludeInvisibleElements_noinvisible_ref.xml
  src/importexport/musicxml/tests/data/testInvisibleNotations.xml
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: MusicXML

#29823 [MusicXML] minor improvements for symbols
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
Labels: MusicXML

#30026 [4.6.0] fixed #29409: Chord symbols should be "above" their fretboard diagrams in arrangement order
  src/engraving/dom/fret.cpp
Labels: vtests

#30029 Port PR #30027
  src/engraving/rendering/score/restlayout.cpp
  vtest/scores/rests-14.mscz
Labels: vtests

#30080 Ignore fret diagrams in slur shape
  src/engraving/rendering/score/slurtielayout.cpp
  vtest/scores/slurs-34.mscz
Labels: vtests, engraving, Pre-release feature issue
