Repository musescore/MuseScore, pull requests merged in 2025-05, with the labels that each got.

#27702 Cross beam spacing improvement
  src/engraving/rendering/score/horizontalspacing.cpp
Labels: vtests

#27571 [MusicXML] import tremolo color
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h
  src/importexport/musicxml/tests/data/testTremolo.xml
Labels: MusicXML

#27569 Improve MeasureBaseList lookup performance
  src/engraving/dom/excerpt.cpp
  src/engraving/dom/mcursor.cpp
  src/engraving/dom/measurebase.cpp
  src/engraving/dom/measurebase.h
  src/engraving/dom/score.cpp
  src/engraving/dom/utils.cpp
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rw/read114/read114.cpp
  src/engraving/rw/read206/read206.cpp
  src/engraving/rw/read400/staffrw.cpp
  src/engraving/rw/read410/staffread.cpp
  src/importexport/bb/internal/bb.cpp
  src/importexport/bww/internal/bww/importbww.cpp
  src/importexport/guitarpro/internal/gtp/gpconverter.cpp
  src/importexport/guitarpro/internal/importgtp.cpp
  src/importexport/guitarpro/internal/importptb.cpp
  src/importexport/mei/internal/meiimporter.cpp
  src/importexport/midi/internal/midiimport/importmidi.cpp
  src/importexport/musedata/internal/musedata.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass1.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass1.h
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/ove/internal/importove.cpp
  src/notation/internal/masternotation.cpp
Labels: performance

#25887 MuseSampler: fixed potential compatibility issues
  src/framework/musesampler/internal/musesamplerresolver.cpp
  src/playback/view/internal/inputresourceitem.cpp
  src/project/internal/projectaudiosettings.cpp
Labels: P1, MuseSounds

#27978 When filling gaps with rests consider local time sig
  src/engraving/dom/cmd.cpp
  src/engraving/rendering/score/beamlayout.cpp
  vtest/scores/beams-32.mscz
Labels: vtests

#28008 Include articulations and fermatas in horizontal spacing calculations
  src/engraving/dom/engravingitem.cpp
  src/engraving/dom/engravingitem.h
  src/engraving/dom/engravingobject.h
  src/engraving/dom/fermata.cpp
  src/engraving/dom/segment.cpp
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/score/autoplace.cpp
  src/engraving/rendering/score/autoplace.h
  src/engraving/rendering/score/chordlayout.cpp
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/horizontalspacing.h
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/tdraw.cpp
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/articulation-17.mscz
  vtest/scores/fermata-5.mscz
  vtest/scores/fermata-6.mscz
Labels: vtests

#28048 Horizontal spacing improvements
  src/engraving/dom/engravingitem.h
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/horizontalspacing.h
  src/engraving/tests/selectionrange_data/selectionrangedelete06_partialnestedtuplets-ref.mscx
Labels: vtests

#28052 [MusicXML] Improve tempo import from Dorico
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass1.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h
  src/importexport/musicxml/internal/musicxml/shared/musicxmltypes.h
Labels: MusicXML

#27919 [MusicXML] prefer smufl glyphs for technical elements
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
Labels: MusicXML

#27538 [MusicXML] fix export of invisible tempo changes
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/tests/data/testExcludeInvisibleElements_noinvisible_ref.xml
  src/importexport/musicxml/tests/data/testInvisibleDirection.xml
  src/importexport/musicxml/tests/data/testInvisibleTempo.xml
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: MusicXML

#27679 [MusicXML] Left align rehearsal mark in import
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.h
Labels: MusicXML

#28155 fix position of repeatDot in Gootville and MuseJazz
  fonts/README.md
  fonts/gootville/Gootville.otf
  fonts/gootville/metadata.json
  fonts/musejazz/MuseJazz.otf
  fonts/musejazz/metadata.json
  src/engraving/rendering/score/tdraw.cpp
Labels: vtests

#28122 New lyrics options
  src/engraving/rendering/score/lyricslayout.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/notation/view/widgets/editstyle.cpp
  src/notation/view/widgets/editstyle.ui
  vtest/scores/lyrics-29.mscz
Labels: vtests
