Repository musescore/MuseScore, pull requests merged in 2025-08, with the labels that each got.

#28644 MuseSampler: hammer-on/pull-off/tapping support
  src/engraving/playback/filters/spannerfilter.cpp
  src/engraving/playback/metaparsers/chordarticulationsparser.cpp
  src/engraving/playback/metaparsers/chordarticulationsparser.h
  src/engraving/playback/metaparsers/internal/spannersmetaparser.cpp
  src/framework/mpe/internal/articulationstringutils.h
  src/framework/mpe/mpetypes.h
  src/framework/mpe/resources/general_strings_articulations_profile.json
  src/framework/musesampler/internal/apitypes.h
  src/framework/musesampler/internal/musesamplersequencer.cpp
Labels: playback, MuseSounds

#29015 Implement modifer parentheses
  src/engraving/data/chords/chords_std.xml
  src/engraving/dom/chordlist.cpp
  src/engraving/dom/chordlist.h
  src/engraving/dom/harmony.cpp
  src/engraving/dom/harmony.h
  src/engraving/rendering/score/harmonylayout.cpp
  src/engraving/rendering/score/harmonylayout.h
  src/engraving/rendering/score/parenthesislayout.cpp
  src/engraving/rendering/score/parenthesislayout.h
  src/engraving/rendering/score/tdraw.cpp
  src/engraving/rendering/score/tlayout.cpp
  src/engraving/rendering/single/singledraw.cpp
  src/inspector/models/notation/frames/fretframe/fretframechordlistmodel.cpp
  vtest/scores/harmony-33.mscz
Labels: vtests

#29170 Prepare engraving tests score reading code for working with proper MS4 scores
  src/engraving/compat/mscxcompat.cpp
  src/engraving/compat/mscxcompat.h
  src/engraving/rw/mscloader.cpp
Labels: tech debt

#29167 Clean up engraving/rw
  src/engraving/CMakeLists.txt
  src/engraving/dom/fret.cpp
  src/engraving/rw/harmonytodiagramreader.cpp
  src/engraving/rw/harmonytodiagramreader.h
  src/engraving/rw/read114/read114.cpp
  src/engraving/rw/read206/read206.cpp
  src/engraving/rw/read302/read302.cpp
  src/engraving/rw/read400/readcontext.cpp
  src/engraving/rw/read400/readcontext.h
  src/engraving/rw/read400/tread.cpp
  src/engraving/rw/read410/harmonytodiagramreader.cpp
  src/engraving/rw/read410/measureread.cpp
  src/engraving/rw/read410/read410.cpp
  src/engraving/rw/read410/readcontext.cpp
  src/engraving/rw/read410/readcontext.h
  src/engraving/rw/read410/staffread.cpp
  src/engraving/rw/read410/tread.cpp
  src/engraving/rw/read460/harmonytodiagramreader.h
  src/engraving/rw/read460/measureread.cpp
  src/engraving/rw/read460/read460.cpp
  src/engraving/rw/read460/readcontext.cpp
  src/engraving/rw/read460/readcontext.h
  src/engraving/rw/read460/tread.cpp
  src/engraving/rw/read460/tread.h
  src/engraving/rw/write/connectorinfowriter.h
  src/engraving/rw/write/twrite.cpp
  src/engraving/rw/write/writecontext.cpp
  src/engraving/rw/write/writecontext.h
  src/engraving/rw/write/writer.cpp
Labels: tech debt

#28221 [MusicXML] add support for hairpin style
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
Labels: MusicXML

#26568 [MusicXML] write bezier points for slurs
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
Labels: MusicXML

#29157 Print MuseSampler logs
  src/framework/musesampler/internal/apitypes.h
  src/framework/musesampler/internal/libhandler.h
  src/framework/musesampler/internal/musesamplerresolver.cpp
Labels: internal, dev

#29263 [MusicXML] import string-mute element
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/tests/data/testStringmute.xml
  src/importexport/musicxml/tests/data/testStringmute_ref.mscx
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: MusicXML

#29332 Refactor some Handbells articulations as playing techiques
  src/engraving/dom/articulation.cpp
  src/engraving/dom/playtechannotation.cpp
  src/engraving/dom/playtechannotation.h
  src/engraving/playback/metaparsers/internal/symbolsmetaparser.cpp
  src/engraving/types/types.h
  src/engraving/types/typesconv.cpp
  src/palette/internal/palettecreator.cpp
Labels: engraving, Pre-release feature issue

#29275 Chord symbol parentheses improvements
  src/engraving/dom/parenthesis.h
  src/engraving/dom/segment.cpp
  src/engraving/rendering/score/parenthesislayout.cpp
  vtest/scores/harmony-35.mscz
Labels: vtests

#29353 Fix out of date padding table for parts
  src/engraving/dom/score.cpp
  src/engraving/engravingproject.cpp
  src/engraving/rendering/paddingtable.cpp
  src/engraving/rendering/paddingtable.h
Labels: vtests

#28156 [MusicXML] export all time signature string components
  src/importexport/musicxml/internal/musicxml/export/exportmusicxml.cpp
  src/importexport/musicxml/tests/data/testTimesig5.mscx
  src/importexport/musicxml/tests/data/testTimesig5_ref.xml
  src/importexport/musicxml/tests/musicxml_tests.cpp
Labels: MusicXML

#29343 [MusicXML] Unify color import
  src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
  src/importexport/musicxml/tests/data/testColors.xml
Labels: MusicXML

#29380 Fix duplicate "To coda (symbol)" items in palette
  src/engraving/dom/property.cpp
  src/engraving/rw/read410/tread.cpp
  src/engraving/rw/read460/tread.cpp
  src/engraving/rw/write/twrite.cpp
  src/engraving/rw/xmlwriter.cpp
  src/engraving/tests/compat114_data/markers-ref.mscx
  src/engraving/tests/compat206_data/markers-ref.mscx
  src/engraving/tests/partialtie_data/coda-ref.mscx
  src/engraving/tests/partialtie_data/volta_coda-ref.mscx
  src/engraving/tests/utils/scorecomp.cpp
  src/engraving/tests/utils/scorecomp.h
  src/engraving/types/propertyvalue.cpp
  src/engraving/types/propertyvalue.h
  src/engraving/types/typesconv.cpp
  src/importexport/guitarpro/tests/data/directions.gp-ref.mscx
  src/importexport/guitarpro/tests/data/directions.gpx-ref.mscx
  src/importexport/mei/tests/data/jump-01.mscx
  src/importexport/mei/tests/data/jump-02.mscx
  src/importexport/musicxml/tests/data/testCodaHBox_ref.mscx
  src/importexport/musicxml/tests/data/testDSalCodaMisplaced_ref.mscx
  src/importexport/musicxml/tests/data/testDSalCoda_ref.mscx
  src/importexport/musicxml/tests/data/testInferCodaII_ref.mscx
  src/importexport/musicxml/tests/data/testInferSegnoII_ref.mscx
  src/importexport/musicxml/tests/data/testTextQuirkInference_ref.mscx
  src/inspector/models/notation/markers/markersettingsmodel.cpp
  src/inspector/models/notation/markers/markersettingsmodel.h
  src/inspector/view/qml/MuseScore/Inspector/notation/markers/MarkerSettings.qml
  vtest/scores/marker-1.mscz
  vtest/scores/marker-2.mscz
  vtest/scores_small/Repeats_Jumps.mscz
  vtest/vtest-compare-pngs.sh
Labels: vtests

#29424 Port stuff
  share/templates/04-Solo/02-Guitar_+_Tablature/02-Guitar_+_Tablature.mscx
  share/templates/04-Solo/03-Guitar_Tablature/03-Guitar_Tablature.mscx
  src/app/configs/data/shortcuts.xml
  src/app/configs/data/shortcuts_azerty.xml
  src/app/configs/data/shortcuts_mac.xml
  src/engraving/dom/box.cpp
  src/engraving/dom/chordrest.cpp
  src/engraving/dom/cmd.cpp
  src/engraving/dom/edit.cpp
  src/engraving/dom/hammeronpulloff.cpp
  src/engraving/dom/hammeronpulloff.h
  src/engraving/dom/score.cpp
  src/engraving/dom/score.h
  src/engraving/dom/spanner.cpp
  src/engraving/rendering/score/alignmentlayout.cpp
  src/engraving/rendering/score/alignmentlayout.h
  src/engraving/rendering/score/chordlayout.cpp
  src/engraving/rendering/score/measurelayout.cpp
  src/engraving/rendering/score/systemlayout.cpp
  src/engraving/rendering/score/tappinglayout.cpp
  src/engraving/rendering/score/tlayout.cpp
  src/engraving/rw/read400/read400.cpp
  src/engraving/rw/read410/read410.cpp
  src/engraving/rw/read460/read460.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/notation/internal/notationinteraction.cpp
  src/notation/qml/MuseScore/NotationScene/internal/EditStyle/HammerOnPullOffTappingPage.qml
  src/notation/view/styledialog/hammeronpullofftappingpagemodel.cpp
  src/notation/view/styledialog/hammeronpullofftappingpagemodel.h
  vtest/scores/hopo-4.mscz
Labels: vtests

#29400 Jazz chords preset refinements
  src/engraving/data/chords/chords_jazz.xml
  src/engraving/dom/chordlist.cpp
  src/engraving/dom/chordlist.h
  src/engraving/dom/undo.cpp
  src/engraving/rendering/score/harmonylayout.cpp
  vtest/scores/musejazz-chords.mscz
Labels: vtests

#29377 Handbells playback part 2 (Swing, Echo, LV, Damp)
  src/engraving/playback/metaparsers/internal/spannersmetaparser.cpp
  src/engraving/playback/metaparsers/notearticulationsparser.cpp
  src/engraving/playback/metaparsers/notearticulationsparser.h
  src/engraving/playback/playbackcontext.cpp
  src/engraving/playback/playbackcontext.h
  src/engraving/playback/playbackeventsrenderer.cpp
  src/engraving/playback/playbackeventsrenderer.h
  src/engraving/playback/playbackmodel.cpp
  src/engraving/playback/renderingcontext.h
  src/engraving/playback/utils/expressionutils.h
  src/engraving/tests/playback/bendsrenderer_tests.cpp
  src/engraving/tests/playback/playbackcontext_data/play_techniques/play_tech_annotations.mscx
  src/engraving/tests/playback/playbackcontext_tests.cpp
  src/engraving/tests/playback/playbackeventsrenderer_data/handbells_let_vibrate.mscx
  src/engraving/tests/playback/playbackeventsrendering_tests.cpp
  src/framework/audio/worker/internal/synthesizers/fluidsynth/fluidsequencer.cpp
  src/framework/audio/worker/internal/synthesizers/fluidsynth/fluidsequencer.h
  src/framework/audio/worker/internal/synthesizers/fluidsynth/soundmapping.h
  src/framework/mpe/internal/articulationstringutils.h
  src/framework/mpe/mpetypes.h
  src/framework/mpe/resources/general_keyboard_articulations_profile.json
  src/framework/mpe/resources/general_percussion_articulations_profile.json
  src/framework/mpe/resources/general_strings_articulations_profile.json
  src/framework/musesampler/internal/apitypes.h
  src/framework/musesampler/internal/musesamplersequencer.cpp
  src/framework/musesampler/internal/musesamplersequencer.h
  src/framework/vst/internal/synth/vstsequencer.cpp
  src/framework/vst/internal/synth/vstsequencer.h
Labels: playback

#29422 Fix slight bend spacing in TAB
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/tlayout.cpp
  vtest/scores/guitarBend-10.mscz
Labels: vtests

#29502 Port stuff
  share/templates/01-General/01-Treble_Clef/score_style.mss
  share/templates/01-General/02-Bass_Clef/score_style.mss
  share/templates/01-General/03-Grand_Staff/score_style.mss
  share/templates/02-Choral/01-SATB/score_style.mss
  share/templates/02-Choral/02-SATB_+_Organ/score_style.mss
  share/templates/02-Choral/03-SATB_+_Piano/score_style.mss
  share/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
  share/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
  share/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
  share/templates/02-Choral/07-Voice_+_Piano/score_style.mss
  share/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
  share/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
  share/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
  share/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
  share/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
  share/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
  share/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
  share/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
  share/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
  share/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
  share/templates/04-Solo/01-Guitar/score_style.mss
  share/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
  share/templates/04-Solo/03-Guitar_Tablature/score_style.mss
  share/templates/04-Solo/04-Piano/score_style.mss
  share/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
  share/templates/05-Jazz/02-Big_Band/score_style.mss
  share/templates/05-Jazz/03-Jazz_Combo/score_style.mss
  share/templates/06-Popular/01-Rock_Band/score_style.mss
  share/templates/06-Popular/02-Bluegrass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
  share/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
  share/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
  share/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
  share/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
  share/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
  share/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
  share/templates/08-Orchestral/03-String_Orchestra/score_style.mss
  src/engraving/dom/engravingitem.cpp
  src/engraving/dom/note.cpp
  src/engraving/dom/stringdata.cpp
  src/engraving/dom/textbase.cpp
  src/engraving/rendering/score/horizontalspacing.cpp
  src/engraving/rendering/score/parenthesislayout.cpp
  src/engraving/rendering/score/tlayout.cpp
  src/engraving/rendering/single/singlelayout.cpp
  src/engraving/style/styledef.cpp
  src/engraving/style/styledef.h
  src/notation/view/styledialog/measurenumberspagemodel.cpp
  vtest/scores/guitarBend-10.mscz
Labels: vtests

#29523 Fix courtesy paren layout on linux
  src/engraving/dom/parenthesis.h
  src/engraving/rendering/score/parenthesislayout.cpp
Labels: os: linux, Pre-release feature issue
